### ISSUE TITLE
Error packaging PCF Sample : Project Reference with output path 0, is not a valid PowerApps Component Type

### ISSUE THREAD

**Issue by radupasol** [microsoft/PowerApps-Samples#105]
I'm getting an error on the last step of packaging the samples - on the 'msbuild' step I'm getting: 
....\microsoft.powerapps.msbuild.solution\1.1.6\build\Microsoft.PowerApps.MSBuild.
Solution.targets(98,5): error : Project Reference with output path 0, is not a valid PowerApps Component Type  [...\TS_MapControl\solutions\solutions.cdsproj]

Tried on MapControl, IframeControl & ImageUploadControl, both on msbuild 15.* and 16.* tool chain

**Comment by mac-windle** [comment]
I am getting the same issue. 

After following the instructions here: 
https://github.com/microsoft/PowerApps-Samples/blob/master/component-framework/README.md

I successfully run `msbuild /t:restore,` and then when running `msbuild` again, i get 2 fails both with the same message as shown in the post above.

**Comment by cyus** [comment]
I am getting the same issue but specific only for TS_ReactStandardControl. The app works on local but when packaging the solution, it seems to be having some trouble with Whole.None type. Other type seems to be OK.

**Comment by cyus** [comment]
Got it!
![image](https://user-images.githubusercontent.com/28690471/79638953-1d613a00-81bb-11ea-9b18-35b841fdd2dd.png)
For some reason when solution folder is initialized, the [SolutionName].cdsproj default version is not  1.*. Just modify that to 1.* then do a msbuild /t:build /restore.

**Comment by Nkrb** [comment]
@cyus Thanks for the help solving the issue. Closing the issue. 
@radupasol Please re-open the issue, if you feel you need more information.
