### ISSUE TITLE
Off-by-one error in Global Discovery sample

### ISSUE THREAD

**Issue by josiahvinson** [microsoft/PowerApps-Samples#110]
The Global Discovery code sample discovers CDS instances for a user, but the line below only shows results if the number of instances is **greater than** 1. It should be **greater than or equal to** 1. I was going through the example and couldn't understand why my one instance wasn't showing up.

https://github.com/microsoft/PowerApps-Samples/blob/eede718128d21d129f539b00b6620584edd95207/cds/webapi/C%23/GlobalDiscovery/GlobalDiscovery/Program.cs#L44

**Comment by Nkrb** [comment]
@josiahvinson Thanks for the feedback. We have updated the docs and pushed live. Closing the issue.
