### ISSUE TITLE
Not able to add additional data-set in manifest

### ISSUE THREAD

**Issue by mattroot87** [microsoft/PowerApps-Samples#127]
Hello,

Is it possible to add an additional data set in the manifest xml?

Thanks!

Matt

**Comment by Nkrb** [comment]
@mattroot87 Yes you can add multiple data sets in a single manifest file. If you have issues, please raise the issue [here](https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/bd-p/pa_component_framework). Closing the issue.
