### ISSUE TITLE
QuickStartCS solution folder have missing files

### ISSUE THREAD

**Issue by lspiguel** [Microsoft/PowerApps-Samples#13]
Please note that QuickStartCS solution on /cds/Xrm Tooling/QuickStartCS/QuickStartCS is missing (at least) these files:

- App.config
- MyOrganizationSdkTypes.cs
- OptionSets.cs
- SampleHelpers.cs
- Files on the LoginUX subfolder

I'll appreciate it if you can fix/upload the missing files.

Thanks for the samples, hope you can fix it.

**Comment by Nkrb** [comment]
@lspiguel Thanks for the feedback. The issue is fixed now.

**Comment by lspiguel** [comment]
Thank you very much!

**Comment by vaibhav21791** [comment]
It seems this issue has been regenerated. I cannot find SampleHelpers.cs file in the solution. 

Kindly upload the missing file. Thanks for your help.  @Nkrb
