### ISSUE TITLE
CDSWebApiService crashes if the response does not contain JSON data

### ISSUE THREAD

**Issue by timrobinson33** [microsoft/PowerApps-Samples#130]
for instance PowerApps-Samples/cds/webapi/C#/CDSWebApiService/CDSWebApiService/CDSWebApiService.cs in the ParseError method

This always calls JObject.Parse but in many cases (e.g. 401), the body will be empty (or I guess in some cases it might be non-json text) so the error handling will itself throw an error. a better technique would be to read the content as a string first, then if the JSON parse fails you can fallback to logging the body as a string

**Comment by JimDaly** [comment]
@timrobinson33 
Great point. We should update this to deal with that possibility.
@phecke has started with some fixes.
We can close this when those are applied.

**Comment by phecke** [comment]
@timrobinson33 I have made some code changes in ParseError() to handle an empty response. You can find the updated code in my working branch pehecke-webapi-sample-update. When I am done with my sample work, I will be merging to master.

I will research checking for valid JSON code before trying the JObject.Parse.

Thanks for your feedback.

**Comment by phecke** [comment]
Reopening this issue until I merge the changes to master.

**Comment by phecke** [comment]
@timrobinson33 The fix is published now.
