### ISSUE TITLE
How to set the profile pic in model driven app.

### ISSUE THREAD

**Issue by manishsg** [microsoft/PowerApps-Samples#132]
Hi PowerApps Team

We had a request to set the profile picture in one of our model driven app.

Please let us know how we can achieve it

Thank you
Manish

![image](https://user-images.githubusercontent.com/1161386/84856095-8ed23300-b01a-11ea-9b2d-e0733bae6980.png)

**Comment by phecke** [comment]
@manishsg Is this about one of our code samples or using the interactive Power Apps web app? Please provide a link to the documentation or sample code that you are having issue with.

**Comment by mansimg** [comment]
Hi @Phecke - if you look at the screen shot of the model driven app. The profile pic at the right can't be displayed.

**Comment by Nkrb** [comment]
@manishsg There is no ay right now to update/add profile pictures in model-driven apps. Please consider submitting an idea in [Power Apps Ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas). Closing the issue.
