### ISSUE TITLE
Operation returned an invalid status code BadRequest

### ISSUE THREAD

**Issue by UM001** [microsoft/PowerApps-Samples#136]
I have a customEntity and run CrmSvcUtil : CRM Service Utility [Version 9.0.0.9340] to create a serviceContext.
Reading data is fine, but if I try to create a new record I get 'Operation returned an invalid status code BadRequest'. I changed by code to use the cdsclient as I had the idea it is related to the serviceContext and I should usd cdsclient.

`           _organizationService.Create(customEntity);
            
            //_serviceContext.AddObject(customEntity);
            //_serviceContext.SaveChanges();`

However, it seems to be related to the related entity for which I had this code in the past:
`var result= new my_customEntity()
                    {
                        //Id = Guid.NewGuid(),
                        my_name = myname,
                        //my_CertificationType = new EntityReference(my_customEntityType.EntityLogicalName, customEntityTypeId),
                        my_SerialNumber = serialNumber,
                        statecode = my_customEntity.Active,
                    };
return result.Id
`
If I remove the my_CertificationType the record is created. However, ID still 0000-0000-000-0000...I guest because Id needs to be defined before calling Create(). Both methods are working with except of the relationship.

Any idea or example how to fix this? I then most likely need to rewrite my code.

**Comment by UM001** [comment]
Are you not forgotten to add EntityReference in the 'Create Request to CDS?'. It looks like the webapi is called. That web api should get some additional information about the related records. Please advice.

Do you have sample?
Do you have sample of strong typed custom entity with CrmSvcUtil 

`/// <summary>

        /// Issues a Create request to CDS

        /// </summary>

        /// <param name="entity">Entity to create</param>

        /// <returns>ID of newly created entity</returns>

        public Guid Create(Entity entity)

        {

            // Relay to Update request. 

            CreateResponse resp = (CreateResponse)ExecuteCdsOrganizationRequest(

                new CreateRequest() 

                { 

                    Target = entity 

                }

                , "Create To CDS via IOrganizationService" 

                , useWebAPI:true);

            if (resp == null)

                throw LastCdsException;



            return resp.id;

        }`

`private OrganizationResponse CdsCommand_WebAPIProcess_Execute(OrganizationRequest req, string logMessageTag)
        {
            if (Utilities.IsRequestValidForTranslationToWebAPI(req)) // THIS WILL GET REMOVED AT SOME POINT, TEMP FOR TRANSTION  //TODO:REMOVE ON COMPELTE
            {
                HttpMethod methodToExecute = HttpMethod.Get;
                Entity cReq = null;
                if (req.Parameters.ContainsKey("Target") && req.Parameters["Target"] is Entity ent) // this should cover things that have targets. 
                {
                    cReq = ent; 
                }
                else if (req.Parameters.ContainsKey("Target") && req.Parameters["Target"] is EntityReference entRef) // this should cover things that have targets. 
                {
                    cReq = new Entity(entRef.LogicalName, entRef.Id); 
                }

                if (cReq != null)
                { `

**Comment by phecke** [comment]
@UM001 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.
 
Closing this issue.

We accept incorrect or missing documentation type of issues here.
