### ISSUE TITLE
Documentation insufficient / samples fail to build

### ISSUE THREAD

**Issue by black-snow** [microsoft/PowerApps-Samples#137]
Hi,

I tried to run the the [IFrame sample component](https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/TS_IFrameControl) following [these](https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/TS_IFrameControl) steps (and the install steps before) but I failed.

First, the install steps were insufficient and I failed at the step `msbuild /t:restore` because I had no `msbuild`. I installed VSCode and not Studio - I guess it comes with Studio. So after a while I found that I could [install](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16) the build tools w\o Studio. I now have `msbuild` (but only via the Power Shell for VS 2019 ...).

Aight, so let's move on.

> Navigate to the folder on your computer where you have downloaded the sample components, and extract the .zip file.

done

> navigate to the sample component folder in the extracted folder that you want to see it in runtime

`F:\PowerApps-Samples-master\component-framework\TS_IFrameControl`

> npm install

no problem

> Create a new folder using the command mkdir <folder name> inside the sample component folder and navigate into the folder using the command cd <folder name>

`mkdir mytest`   
`cd mytest`

> pac solution init --publisher-name <Name of the publisher> --publisher-prefix <Publisher prefix>

`pac solution init --publisher-name me --publisher-prefix pfx` 

> pac solution add-reference --path <Path to the root of the sample component>

The sample component is the iframe thing, so `pac solution add-reference --path ../`. Am I missing something? The doc could be more explicit and say "in this case that's the parent directory" or something like that.

> To generate a zip file from your solution project, you need to cd into your solution project directory and build the project using the following command: msbuild /t:restore

Wait, what's the "solution project directory"? Isn't this where we are right now? So no `cd`ing needed.

Alright, let's do this: `msbuild /t:restore` 

Everything is green, seems legit.

> Again, run the command "msbuild".

That should be easy:

```
  npm run build -- --noColor --buildMode development --outDir "F:\PowerApps-Samples-master\component-framework\TS_IFrameControl\out\controls" --buildSource MSBuild

  > pcf-project@1.0.0 build F:\PowerApps-Samples-master\component-framework\TS_IFrameControl
  > pcf-scripts build "--noColor" "--buildMode" "development" "--outDir" "F:\PowerApps-Samples-master\component-framework\TS_IFrameControl\out\controls" "--buildSource"
   "MSBuild"

  Der Befehl "pcf-scripts" ist entweder falsch geschrieben oder
  konnte nicht gefunden werden.
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! pcf-project@1.0.0 build: `pcf-scripts build "--noColor" "--buildMode" "development" "--outDir" "F:\PowerApps-Samples-master\component-framework\TS_IFrameCont
  rol\out\controls" "--buildSource" "MSBuild"`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the pcf-project@1.0.0 build script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

  npm ERR! A complete log of this run can be found in:
  npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-07-14T08_32_40_761Z-debug.log
```

Nope. There is a `pcf-scripts` inside `TS_IFrameControl/node_modules/.bin` but `msbuild` does not seem to recognize this.

So, what am I missing here?

**Comment by black-snow** [comment]
Also it seems like the folder `TS_IFrameControl/TSIFrameControl` has gone ...

**Comment by black-snow** [comment]
Some additional information:

node v14.5.0
npm 6.14.5
Win10 Pro 19041.329

**Comment by black-snow** [comment]
Hey @Nkrb any news on this? It's a real blocker for us right now.

**Comment by Nkrb** [comment]
@black-snow Please raise the issue [here](https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/bd-p/pa_component_framework), our development team will help you solve the problem.

**Comment by black-snow** [comment]
> 
> 
> @black-snow Please raise the issue [here](https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/bd-p/pa_component_framework), our development team will help you solve the problem.

https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Cannot-build-sample-components/m-p/632175#M3012

**Comment by black-snow** [comment]
I finally figured it out. While `node_modules/.bin` was populated all the scripts inside it were empty (for whatever reason). Deleting and `npm i` again didn't recreate `.bin` but a complete wipe of `node_muldes` and a reinstall did the trick. I was then able to follow the last steps to create the zip.
