### ISSUE TITLE
Is it possible to use the react app component like a normal react app with multiple components and or routes

### ISSUE THREAD

**Issue by xtianus79** [microsoft/PowerApps-Samples#140]
I am noticing that all of the code base for these examples are such that the entire code project is in the index.ts file. A normal react act usually references the bootstrap code base, <app /> in the index.ts file as such:

```javascript
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
```

Can a similar practice be done for these powerapp components as well?

**Comment by Nkrb** [comment]
@xtianus79 Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.
