### ISSUE TITLE
GenerateEntityDiagram performance

### ISSUE THREAD

**Issue by andrewtheart** [microsoft/PowerApps-Samples#143]
Hello,

I am struggling with the performance of GenerateEntityDiagram.

I have a good machine - quad core, 16GB RAM.

I am connected to an online version of Dynamics 365 that has little daily usage. 

I am debugging the program in VS 2019 and I have processed 142 entities in almost two straight days of continuous runtime (46 hours).

Visio has been running in the background the entire time at around 12% CPU.

Is this performance expected? Is Visio the bottleneck in this program (my guess), or is it something else? 
And if it is Visio - how in the world is it taking 20 minutes per entity to create a diagram? 

Any other tips?

**Comment by Nkrb** [comment]
@andrewtheart Thanks for the feedback. Yes this is expected. We recommend you to only generate entity diagram for only required entities and not all the entities in the system. Closing the issue. If you need further help, please reopen the issue or open a new issue.
