### ISSUE TITLE
Issue with TSImageUploadControl - Default image not found error

### ISSUE THREAD

**Issue by rjn71** [microsoft/PowerApps-Samples#144]
I've deployed the TSImageUploadControl code from github. The upload is working fine. However the default image is not being set. I'm getting the error "Image not found" in this line 

this._context.resources.getResource(DefaultImageFileName, this.setImage.bind(this, false, "png"), this.showError.bind(this));

After the call to getResource, the error function showError is called which displays the image not found message. I can see the default.png in the "img" folder. I'm unable to find the actual exception that is thrown by getResource. Are you able to help?

**Comment by Nkrb** [comment]
Thanks for the feedback. Please raise the issue in the [community forum](https://powerusers.microsoft.com/t5/PowerApps-Component-Framework/bd-p/pa_component_framework). Our developers will help you resolve the issue. Closing the issue.

**Comment by rjn71** [comment]
Thanks @Nkrb . I've posted the issue here - https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Issue-with-PCF-TSImageUploadControl-Default-image-not-found/td-p/641777

Hope someone from dev team can pick this. Looks like a bug

**Comment by rjn71** [comment]
I've reopened the issue as I  haven't got any help from the community. Hope you can look into this
