### ISSUE TITLE
Issue with the name 'accountId' not exist 

### ISSUE THREAD

**Issue by yellowhot007** [microsoft/PowerApps-Samples#148]
for instance PowerAppsSamples/edit/master/cds/orgsvc/C%23/EarlyBoundEntityOperations/EarlyBoundEntityOperations/SampleProgram.cs
In the row 36 and row 43 ,the name 'accountId' does not exist in the current context.

**Comment by Nkrb** [comment]
@yellowhot007 Are you getting the error: Name accountId doesn't exist in the current context? We don't see that issue from our side. Can you give more details.

**Comment by Nkrb** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
