### ISSUE TITLE
CDSWebApiService

### ISSUE THREAD

**Issue by MiraGhaly** [microsoft/PowerApps-Samples#156]
I am using the class in my code to create a contact but the URI is never returned and it do not respond back

**Comment by JimDaly** [comment]
@MiraGhaly 
Can you share the code you are using?
Are you using the PostCreate method?

Can you capture a trace using Fiddler?

**Comment by MiraGhaly** [comment]
@JimDaly 
Here is the code:
` // POST: api/Test
        public string Post([FromBody]string value)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["Connect"].ConnectionString;
            ServiceConfig config = new ServiceConfig(connectionString);

            using (CDSWebApiService svc = new CDSWebApiService(config))
            {
                //  Console.WriteLine("--Starting Basic Operations--");

                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;

                //Create a contact
                var contact1 = new JObject
                        {
                            { "firstname", "Mira" },
                            { "lastname", "WEB API" }
                };
               return svc.PostCreate("contacts", contact1).ToString();

           
            }

        }`
It is worth to note that i have made one change too the OAuthMessageHandler class to Authenticate using Client Credentials.

**Comment by JimDaly** [comment]
It isn't expected that you would wrap up the CDSWebAPIService inside a method like the **Post** method you are using. It is expected that you re-use the methods it provides for multiple operations as demonstrated in the BasicOperations sample. It is a service that demonstrates best practices around managing a re-usable HttpClient and service protection limits.

Instantiating the service for a single operation call is not very efficient.

You are saying that it works, but you just aren't getting the Uri returned as a string. I would refactor your code to change this part:

` return svc.PostCreate("contacts", contact1).ToString();`

Instead use:

```
var uri =  svc.PostCreate("contacts", contact1);
return uri.ToString();
```
This way you can set your breakpoint on the return line and verify that the URI was returned from the svc.PostCreate call.

Finally, Why the `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;` line?
If you are using .Net Framework > 4.5 it shouldn't be necessary.
