### ISSUE TITLE
TSWebApi Sample is missing uses-feature

### ISSUE THREAD

**Issue by BetimBeja** [microsoft/PowerApps-Samples#157]
The sample component TSWebApi does not specify the uses-feature for WebApi and is not working, you get the following error in the `PowerApps component framework Test Environment`
![image](https://user-images.githubusercontent.com/11160171/93665984-e9948400-fa7a-11ea-8bb8-ef341dd71ff7.png)

**Comment by Nkrb** [comment]
@BetimBeja Thanks for the feedback. Manifest file is updated to include the use-feature. Closing the issue. If you need further help, please reopen or create a new issue.
