### ISSUE TITLE
Text being inserted that breaks files "<<<<<<< HEAD" ">>>>>>> e17f0bedd03f33aec18be3f488aee58b5c2fbc6a"

### ISSUE THREAD

**Issue by RedsGT** [microsoft/PowerApps-Samples#17]
Example:

<<<<<<< HEAD

    

=======

    

>>>>>>> e17f0bedd03f33aec18be3f488aee58b5c2fbc6a

**Comment by JimDaly** [comment]
Fixed the merge conflict artifact
