### ISSUE TITLE
Code samples are outdated and do not reflect the current functionality

### ISSUE THREAD

**Issue by kkjasoncheung** [microsoft/PowerApps-Samples#174]
The code sample here says that each entity can only have one attribute of type image.

https://github.com/microsoft/PowerApps-Samples/blob/b31a588958bdd7dd5fb8d8d1545c1fa5567dc85c/cds/orgsvc/C%23/SetRetrieveImages/SetRetrieveImages/SampleMethods.cs#L79

However, I've been able to create a custom entity that has two attributes with type file. Please see image  #below.

![image](https://user-images.githubusercontent.com/22229174/109337120-55e98f80-7832-11eb-8f1b-adf5046b21cb.png)

**Comment by Nkrb** [comment]
Thanks for contacting us. We have updated the docs and pushed it live. Closing the issue. If you need further help, please reopen or create a new issue.
