### ISSUE TITLE
XrmTooling oAuth2.0 error

### ISSUE THREAD

**Issue by anbhar** [microsoft/PowerApps-Samples#177]
The XrmLoginWindow control isn't updated to use oAuth2.0.. Also.. you misspelled "Trust" in the error message.. 
![image](https://user-images.githubusercontent.com/50177536/111348882-04753900-8657-11eb-96e0-8e2d93c5640b.png)

**Comment by Nkrb** [comment]
@anbhar Thanks for contacting us. Can you let us know the sample you are trying. If you are connecting to an org using the login screen, can you update the Nuget packages to latest versions and see if you get this issue?

**Comment by anbhar** [comment]
Hi @Nkrb , I have the latest "Microsoft.CrmSdk" Nuget packages installed, still have the same problem, could it be that the new packages for Wave 1 are yet to be released?

I'm using the "PowerApps-Samples/cds/Xrm Tooling/Quick start for XRM Tooling API/" sample as base

**Comment by MattB-msft** [comment]
@anbhar You can get around the issue by updating both the XrmTooling.CoreAssemblies and the Microsoft.Crmsdk.CoreAsseblices Nugets.  

The team will get the Error message fixed,  sorry about that,  And we will update the samples to use current nuget packages going forward to resolve future issues like this.
