### ISSUE TITLE
Unable to Login to Dynamics CRMOrganizationWebProxyClient is null

### ISSUE THREAD

**Issue by umerjaved** [microsoft/PowerApps-Samples#179]
I am trying to run a sample from CDS(QueryWorkingHours) and unfortunately the code keeps failing when trying to connect to Dynamics 365. I get Prompt to connect to Dynamics 365. I provide credentials and second factor authentication(code) however when debugging the connection always return false with below error. I have even tried specifying the TLS protocol explicitely and set the .Netframework version to be 4.6.2 however no luck. 

Unable to Login to Dynamics CRMOrganizationWebProxyClient is null

**ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;**
                service = new CrmServiceClient(GetConnectionStringFromAppConfig("Connect"));

enabled connection string in app.config:

   <add name="Connect" connectionString="
  AuthType=OAuth;
  Username=XXXXX;
  Url=https://XXX.crm11.dynamics.com;
  AppId=XXXXXXXXXXXXXXXXXXXXXXXXXXXX;
  RedirectUri=https://localhost;
  TokenCacheStorePath=C:\Devops\MyTokenCache;
  LoginPrompt=Auto"/>

Any idea what is wrong here?

Thanks

**Comment by umerjaved** [comment]
Debugging the code therefore getting the error below:

![image](https://user-images.githubusercontent.com/16427070/112227200-2f4b2880-8c27-11eb-937a-a1b04ab87730.png)

**Comment by Nkrb** [comment]
@umerjaved Thanks for contacting us. Can you change the  parameter `LoginPrompt=Never` in the connection string and see if you can run the code.

**Comment by umerjaved** [comment]
> @umerjaved Thanks for contacting us. Can you change the parameter `LoginPrompt=Never` in the connection string and see if you can run the code.

@Nkrb thanks. I tried your suggestion, however getting below error now
![image](https://user-images.githubusercontent.com/16427070/113899483-c2a66100-97c4-11eb-87ca-466c2a6d7597.png)

**Comment by Nkrb** [comment]
@umerjaved Can you remove the Authentication factor for the org and see.  We don't see any issues running the exact code.

**Comment by umerjaved** [comment]
Hi @Nkrb ,

Sorry I missed responding to this question, Can I confirm you mean remove second factor authentication from the tenant and then test?
Also can you tell this code is tested for organisation where MFA is enabled in the tenant?

Thanks
Umer
