### ISSUE TITLE
Error registering model endpoint with AI Builder

### ISSUE THREAD

**Issue by julians1966** [microsoft/PowerApps-Samples#182]
Step 2 of https://github.com/microsoft/PowerApps-Samples/tree/master/ai-builder/BringYourOwnModelTutorial

at cell 
```
from azureml.core import Workspace
ws = Workspace.from_config()
print(ws.name, ws.resource_group, ws.location, ws.subscription_id, sep = '\n')
```
TypeError: <lambda>() missing 1 required positional argument: 'x'

[errorlog.txt](https://github.com/microsoft/PowerApps-Samples/files/6369571/errorlog.txt)

**Comment by rohitbhoopalam** [comment]
Please try restarting the Kernel (step 1) and start running from cell 2 as shown in the pic (step 2) after entering Power Apps environment name. 
![image](https://user-images.githubusercontent.com/1941471/116461995-d110f700-a81d-11eb-8d2c-0d7cfd156c62.png)

Please let us know if you are still facing this issue.

**Comment by julians1966** [comment]
Hi
That worked but I now get an error on the final cell
`TemplateNotFoundException: This capability is not available / enabled in this environment. Please contact the Environment owner / administrator`

**Comment by julians1966** [comment]
Problem was my organization was not enabled for the preview. The organization has been enabled and the steps work correctly
