### ISSUE TITLE
Regarding Import Complex Data Map

### ISSUE THREAD

**Issue by mdnazirahmed007** [microsoft/PowerApps-Samples#186]
Hi Team,

I have been trying to use "Import Complex Data Map"  c# code to update csv file data into dynamics365.
I understand that we can create records using "Import Complex Data Map"  c# code , but what if we need to update records using the same code. can we do that. 
And Also can we use "Execute Multiple Request" to make the process faster.

**Comment by Nkrb** [comment]
@mdnazirahmed007 Thanks for reaching to us. If you want to update the records that are already in Dataverse, you can use the `IOrganizationService. Update` method, by retrieving the records you want to update. You use Execute Multiple request method to make the process faster if you have more records. You can see the Execute Multiple request sample. Closing the issue. If you need further help, please reopen or create a new issue.
