### ISSUE TITLE
Naming of imported examples is not consistent

### ISSUE THREAD

**Issue by lesyk** [microsoft/PowerApps-Samples#190]
![image](https://user-images.githubusercontent.com/818588/118839142-8e938500-b8c6-11eb-85cc-d2381576f66d.png)
![image](https://user-images.githubusercontent.com/818588/118839199-9b17dd80-b8c6-11eb-89b0-64334ecd5baa.png)

**Comment by phecke** [comment]
@lesyk Which sample are you referring to?
