### ISSUE TITLE
Unable to connect to instance of Dynamics Instance

### ISSUE THREAD

**Issue by sumiticfai196** [microsoft/PowerApps-Samples#198]
Was trying to connect to Dynamics CRM Instance using the following below settings but it always fails 

add name="Connect"
 connectionString="
  AuthType=OAuth;
  Username=sumit@sumit9922.onmicrosoft.com;
  Url=https://sumit9922.crm.dynamics.com;
  Password=Autogreen@**;
  AppId=fa925963-a2b3-40e6-a7f7-e01b0dc3***;
  RedirectUri=https://sumit9922.crm.dynamics.com;
  TokenCacheStorePath=C:\MyTokenCache;
  LoginPrompt=Auto"

Can you please suggest if anything specific am missing in here or steps to resolve the same.
Have registered the Dynamics Instance as App in AZURE

![image](https://user-images.githubusercontent.com/11889749/122655934-435dd380-d10b-11eb-9c18-1ea87e80cf4b.png)

Looking forward for your positive response

**Comment by Nkrb** [comment]
@sumiticfai196 Thanks for reaching to us. I see that the APP ID values has * mark which shouldn't be there. Please remove it and try to sign in to the environment again.

**Comment by phecke** [comment]
@sumiticfai196 

Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

You can also try posting your issue to one of the developer forums.

We accept incorrect or missing documentation and sample code issues.
 
Closing this issue.
