### ISSUE TITLE
Sending Parameters from host to power app via sdk

### ISSUE THREAD

**Issue by ngGuerrilla** [microsoft/PowerApps-Samples#199]
When using an iframe you can pass parameters (context) to a power app from the host application which allows for better integrations. Is there a way to achieve this via the powerappsplayer npm package? I have searched high and low and cannot find any documentation or example for this basic functionality.

**Comment by phecke** [comment]
@ngGuerrilla Sorry, but we cannot help you with that. We handle documentation issues here.

I suggest you post your question in one of the Power Apps developer forums.
