### ISSUE TITLE
PCF using Angular third party libraries 

### ISSUE THREAD

**Issue by patilravikiran** [microsoft/PowerApps-Samples#208]
Hi,

I do not see any documentation on how to create PCF  using third party libraries  like Agular framework. We have samples but not exact procedure. Can you please help me to create pcf using Angular framework.

**Comment by lesyk** [comment]
This might be helpful: https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/angular-flip-control

**Comment by patilravikiran** [comment]
@lesyk I have seen this example already, but I am not sure how we can embed Angular within pcf component.

**Comment by patilravikiran** [comment]
Can anyone help?

**Comment by lesyk** [comment]
Within [index.ts L63-L118](https://github.com/microsoft/PowerApps-Samples/blob/4e41d77925422ab31c3a77475a970498c448d2d2/component-framework/AngularJSFlipControl/AngularJSFlipControl/index.ts#L63-L118) you have initialization and creation of angular. From there add components and use updateView for getting data from CE.

Does it help?

**Comment by Nkrb** [comment]
@patilravikiran Closing the issue. If you need further help, please reopen or create a new issue.
