### ISSUE TITLE
Unexpected error while trying to import .txt file in PowerApps entities

### ISSUE THREAD

**Issue by zachrenwick** [microsoft/PowerApps-Samples#21]
I'm getting an error when attempting to load the .txt files for the online shopper intention example.

When I click "browse", the UI errors out :(

![image](https://user-images.githubusercontent.com/26368788/59232747-88ed7a80-8b9a-11e9-92a8-1b50deeb3f80.png)

**Comment by KumarVivek** [comment]
@zachrenwick  Please note that you do not need to download the CSV files, but rather link the raw URL of the CSV files during the data import flow. We have update the instructions accordingly in the topic: https://docs.microsoft.com/en-us/ai-builder/binary-classification-data-prep

Closing the issue.
