### ISSUE TITLE
FCB 'EnableRegionalDisco' is disabled error trying to login using the QuickStartXRMToolingWPFClient login control

### ISSUE THREAD

**Issue by donschia** [microsoft/PowerApps-Samples#210]
QuickStartXRMToolingWPFClient and everything we have built using this same Common Login Control (i.e. https://www.inogic.com/blog/2016/06/common-login-control-for-dynamics-crm/) fails with this **FCB EnableRegionalDisco** error.  Other custom apps we had could be fixed by rebuilding with latest SDK DLLs or changing our connection strings a bit, but we cannot get anything using this control to connect anymore.  

Does anyone out there have a fix to allow using this login control after June when Microsoft removed the regional discovery service replacing it with the global discovery service:?

Thank you!

**Comment by sanjeev40084** [comment]
@donschia i got the same error when i cloned the repo and ran the sample code to assign security role. I got it fixed by updating all the Microsoft.CRM.x.x nuget packages to latest version. See if that works for you.

**Comment by donschia** [comment]
@sanjeev40084 Right on!  I wasn't having any luck until I rebooted plus I did a CLEAN build with the latest nuget packages.  Now I finally am able to connect to Dynamics online! Thanks so much for confirming the fix.
