### ISSUE TITLE
CDS Relationships between Flow_ Approvals and Workflow

### ISSUE THREAD

**Issue by leondarl** [microsoft/PowerApps-Samples#216]
Dear MS Power Apps and Dataverse Experts and friends,

 I hope all is well !!
I hope I am on the right channel.
I am interested in relating the Approvals to the Workflow and I am having difficulty.
I need to be able to point to the workflow information for each approval  or vise versa.
I have identified the msdyn_flow_flowapproval_flowname column that carries the unique flow  ID.
I am looking at the workflow table and I can't seem to find the equivalent ID to link to.
Can anyone please shed some light.
I can't find any good documentation about the  tables and columns for Dataverse.
Please share with me if you have some good pointers.

With much appreciation
Stay safe
Thank you
Leonidas

**Comment by phecke** [comment]
@leondarl 
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

You can also try posting your issue to one of the developer forums.

We accept incorrect or missing documentation and sample code issues.

I did forward your issue to the Flow technical writer. Perhaps he will have some suggestions.
