### ISSUE TITLE
broken link- import the solution

### ISSUE THREAD

**Issue by lubna-thomas** [microsoft/PowerApps-Samples#228]
The link is broken for "import the solution"
Here is the correct URL:
https://docs.microsoft.com/en-gb/powerapps/maker/data-platform/import-update-export-solutions

Thanks

**Comment by phecke** [comment]
@lubna-thomas What code sample are you referring to?

**Comment by phecke** [comment]
@lubna-thomas component-framework > README.md ?

**Comment by JimDaly** [comment]
Fixed
