### ISSUE TITLE
Delete solution: More friendly message

### ISSUE THREAD

**Issue by herr-mueller** [microsoft/PowerApps-Samples#230]
When using the "Delete Solution" task, the task terminates with error message "_##[error]Index was out of range. Must be non-negative and less than the size of the collection._"

It would be more user-friendly to have a message like "_Solution {xyz} could not be deleted because it is not available on the environment._"

**Comment by Nkrb** [comment]
@herr-mueller Thanks for reaching to us. We will update the sample to have better error messages as you suggested.

**Comment by phecke** [comment]
@herr-mueller Which code sample are you referring to?

**Comment by phecke** [comment]
@herr-mueller Closing this issue as it has been responded to by Nkrb.
