### ISSUE TITLE
Upload PneumoniaDetection zipped folder failed

### ISSUE THREAD

**Issue by rhpoon** [microsoft/PowerApps-Samples#232]
From within AzureML notebook:

I have to download the whole repository and upload the particular folder to get it works.

Upload the unzipped folder  or just upload the zipped folders both wont work (dont have the right content). Have i done anything wrong or it is the zipped file's problem?

**Comment by phecke** [comment]
@rhpoon Please identify the code sample that you are referring to.

**Comment by phecke** [comment]
@rhpoon No response, closing this issue.
