### ISSUE TITLE
Import component failure

### ISSUE THREAD

**Issue by dancohendell** [microsoft/PowerApps-Samples#235]
Error: Import Solution Failed: CustomControl with name SampleNamespace.CanvasGrid failed to import with error: Principal user (Id=**************************************, type=8, roleCount=3, privilegeCount=2358, accessMode=0), is missing prvCreateWebResource privilege (Id=bd57cfa5-8495-4b3e-b358-da246ba797b5) on OTC=9333 for entity 'webresource'

I have system customizer privileges; however it is not pushing the component into the environment - any guidence?

**Comment by JimDaly** [comment]
@dancohendell 
Are you experiencing a problem with one of the samples we have published?

**Comment by JimDaly** [comment]
Closing since no response.
