### ISSUE TITLE
Timeline Custom Connector - Filtering based on timeline search

### ISSUE THREAD

**Issue by akaskela** [microsoft/PowerApps-Samples#242]
In the timeline custom connector, the data set isn't filtered based on the search terms in the timeline control. Is there any way to get that search term from the Timeline so I can filter it within the web resource? It's not available on the request object coming in to getRecordsData and you can't get it in a supported way by reading the form controls.

**Comment by phecke** [comment]
@akaskela Is this issue related to one of our code samples? Is so, which one?

**Comment by akaskela** [comment]
@phecke no, I was asking about the ability to filter the custom connector based on the timeline's search term. Looks like the documentation page was updated April 2nd with details about filtering. The sample code was also updated to include this ability. Closing this as complete.
