### ISSUE TITLE
Upgrading holding solution - Error

### ISSUE THREAD

**Issue by IbrahimElSayed1** [microsoft/PowerApps-Samples#260]
We received the following error while upgrading a holding solution. We are not entirely sure whether the issue is from the Power Platform Tools or Not. Thank you for the support.

![image](https://user-images.githubusercontent.com/103506329/162954883-29d7e7e0-e9e7-48e0-bd3e-d2d1a4e44788.png)

**Comment by phecke** [comment]
@IbrahimElSayed1 Sorry, but we do not provide product support here. If you have a question about a code sample, find a code sample bug, or would like to see us add a new sample, let us know.
