### ISSUE TITLE
Error on CDS patch function

### ISSUE THREAD

**Issue by umerjaved** [microsoft/PowerApps-Samples#265]
Error	CS0103	The name 'SendAsync' does not exist in the current context

The above error is happening when performing update on CDS record.  It is happening within the method(PostAsync) in the following class

CDSWebApiService

Can somebody please help to resolve it?
Thanks

**Comment by JimDaly** [comment]
@umerjaved 
Which sample are you running when you get this error?

**Comment by JimDaly** [comment]
@umerjaved 
The CDSWebApiService is a sample that encapsulates re-usable calling patterns into methods.

The CDSWebApiService class is only tested in the context of the samples published here. If you are re-using it in a different project, you might run into issues not encountered in the development of these samples. As a sample, the idea is that you can borrow some of the patterns demonstrated in your own code.

If you are having issues running any of the samples that depend on CDSWebApiService, please re-open this issue.
