### ISSUE TITLE
ADAL is DEPRECATED so the QuickStart for Dynamics 365 is invalid

### ISSUE THREAD

**Issue by jrichview** [microsoft/PowerApps-Samples#275]
QuickStart app needs to be updated.  NuGet shows Microsoft.IdentityModel.Clients.ActiveDirectory is deprecated.

**Comment by phecke** [comment]
@jrichview Yes, ADAL v1.0 is deprecated (just this month) so no new features are being added. Even after support ends for that library sometime in the future, that library will still be available to use.

ADAL v2.0 (also known as MSAL) is recommended for new development.

We have quickstart code samples that show direct use of ADAL and MSAL authentication under cds\webapi\C#\QuickStart. If you use our SDK CrmServiceClient or ServiceClient classes for authentication, your code is shielded from any fluctuations in the underlying authentication libraries. We also have .NET Core code samples, which use the ServiceClient class and MSAL, at cds\orgsvc\C#-NETCore\ServiceClient.
