### ISSUE TITLE
LinearInputControl - Unexpected Behaviour

### ISSUE THREAD

**Issue by AshishGupta11011** [microsoft/PowerApps-Samples#291]
While using this component , the knob on input control doesn't move to the value of bound property. 
I tried the following :  
- I tried changing the bound property value , the knob was moving to the property value. But once I move the knob directly, then changing the property value  doesn't move the knob in the input control (Althought label below the input control is getting updated). I tried debugging using chrome developer tools , value attribute in the html element is changing but still knob on the input control is stuck.
![image](https://user-images.githubusercontent.com/65274347/178693931-20bf5382-c996-4e8e-8241-d669d755e1a7.png)

**Comment by JimDaly** [comment]
Looking for the dev who wrote this sample.

**Comment by JimDaly** [comment]
This commit includes a change that should fix this [Update index.ts of LinearInput control](https://github.com/microsoft/PowerApps-Samples/pull/301/commits/434fdae076847e5db52d2d9533baf2472d39857f).

@AshishGupta11011 
Can you confirm it is working for you now?

**Comment by AshishGupta11011** [comment]
@JimDaly 
Thanks , It works perfectly now !
