### ISSUE TITLE
The cds orgsvc samples contain deprecated nuget references

### ISSUE THREAD

**Issue by ozdemir-mehmet** [microsoft/PowerApps-Samples#299]
The orgsvc samples contain references to:

Microsoft.IdentityModel.Clients.ActiveDirectory that should be updated to: Microsoft.Identity.Clienthttps://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/5.2.9?_src=template

Here's an example project:
https://github.com/microsoft/PowerApps-Samples/tree/master/cds/orgsvc/C%23/ConsoleAppTemplate/ConsoleAppTemplate

Are there an plans to fix this? As per notes on the Nuget page:

Additional Details
Please note, a newer package is available Microsoft.Identity.Client.
This package will continue to receive critical bug fixes until December 2022, we strongly encourage you to upgrade.

**Comment by phecke** [comment]
@ozdemir-mehmet  Nothing wrong with the sample. Our XrmTooling APIs use ADAL authentication internally. That is why the package is part of the build. As long as you are calling our API's, your code is fine. If you manage authentication directly, then you would want to use MSAL as ADAL is deprecated.

More information: [Transition apps to Dataverse ServiceClient](https://docs.microsoft.com/power-apps/developer/data-platform/sdk-client-transition)
