### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by mkalinovTC** [microsoft/PowerApps-Samples#318]
Hello @JimDaly and community,

I have forked  the Samples for Dataverse part. Compilation of any solution fails due to absence of proper references (using) in cs files.

WebAPIService Service class does not contain definitions of Retrieve, Create and other methods but they are refenced in samples.

Is there something I miss?

**Comment by JimDaly** [comment]
@mkalinovTC 
Thanks for reporting this.

First thing, please make sure you are using VS 2022. If you are using VS 2019 it won't work correctly since these are .NET 6.0 samples.

Second, can you tell me exactly which solution you tried to open and what you saw?

**Comment by mkalinovTC** [comment]
@JimDaly 
Thanks Jim, 
I use VS 2019 with .NET 6.0 (Preview 4, May 2022) installed and functional.
The first  solution I tried to open is WebAPIService itself.
More then 200 files in the solution are missing references. 
For example, the attached screenshot shows Messages/InitializeFromRequest.cs which lacks:

using System;
using System.Collections.Generic;
using System.Net.Http;

Regarding the create, update etc u're correct, it happens because  WebAPIService  cannot be compiled.

![Capture](https://user-images.githubusercontent.com/77283662/191025155-1cc4a574-0d8b-4a06-be51-66b7c573a46c.JPG)
.

**Comment by JimDaly** [comment]
@mkalinovTC 
You need to use VS 2022. These projects were developed and tested only using VS 2022.
You can use [Visual Studio Community](https://visualstudio.microsoft.com/vs/community/).
See : [https://dotnet.microsoft.com/en-us/download/dotnet/6.0](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)

![image](https://user-images.githubusercontent.com/6353736/191069357-f712e4c6-9438-4252-a3c8-9a3fbc316558.png)

**Comment by mkalinovTC** [comment]
Thanks Jim, u're cotrrect

**Comment by JimDaly** [comment]
Please let us know if you run into any other issues.

**Comment by mkalinovTC** [comment]
Hmm, I try to move the to OAuth2 S2S. I see the only Microsoft.IdentityModel.Clients has option of client secret authentication. All MSAL options are for user and/or B2C. Shall we stay with previous Microsoft Identity platform or I miss something again?

**Comment by JimDaly** [comment]
@mkalinovTC 
You shouldn't stay on ADAL.
This sample doesn't focus on Authentication. As called out here: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/samples/webapiservice 

> This library does not:
> 
> - Manage authentication. It depends on a function passed from an application that will provide the access token to use. All Web API samples depend on a shared [App class](https://github.com/microsoft/PowerApps-Samples/blob/master/dataverse/webapi/C%23-NETx/App.cs) that manages authentication using the [Microsoft Authentication Library (MSAL)](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-overview). MSAL supports several different types of authentication flows. These samples use the [Username/password (ROPC)](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows) flow for simplicity but this is not recommended. For your apps, you should use one of the other flows. More information: [Authentication flow support in the Microsoft Authentication Library](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows).

In other words, the sample expects to be passed a function that will return an access token. How that token is generated is up to the developer.

Other than registering the application using AAD and granting the appropriate permissions, the rest is all about using MSAL. You should find resources needed here: [Authentication flow support in MSAL](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows)
