### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by ziron999** [microsoft/PowerApps-Samples#327]
https://github.com/microsoft/PowerApps-Samples/blob/PowerApps-Samples does not exist? 404 error

**Comment by ziron999** [comment]
This was just to inform you the link on https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx/BasicOperations is incorrect currently.

**Comment by JimDaly** [comment]
@ziron999 
Thanks. I think I have fixed it.
