### ISSUE TITLE
Fetch Xml request returns 'Not Found'

### ISSUE THREAD

**Issue by mkalinovTC** [microsoft/PowerApps-Samples#329]
We try to use FetchXMl to query due to OData4 issue with  predefined expression like (Microsoft.Dynamics.CRM.NextXDays etc).
FetchQuery falls with "Not Found".
As u can see in the first screenshot query is fine and contains proper based url. Base url sets ok according to debugger. The query works fine using browser.
![image](https://user-images.githubusercontent.com/77283662/196246144-18a80b33-618c-4217-bbc8-3be09307b151.png)

But, according to error, request looses proper crm based url:
![image](https://user-images.githubusercontent.com/77283662/196246580-f2931b4c-112a-4d26-ae23-667a93144816.png)

**Comment by JimDaly** [comment]
@mkalinovTC 

I see you are sending the request in a batch, which is what the Service.FetchXml method does.
The code for this method is here: [WebAPIService/Methods/FetchXml.cs ](https://github.com/microsoft/PowerApps-Samples/blob/master/dataverse/webapi/C%23-NETx/WebAPIService/Methods/FetchXml.cs).

When you send a BatchRequest, you need to include the [Service.BaseAddress property](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx/WebAPIService#baseaddress-property). This is because relative URLs are not allowed for Multipart content. See [ToMessageContent method](https://github.com/microsoft/PowerApps-Samples/blob/c1539e4573468fa4efe9f527f78e7cf918095ac1/dataverse/webapi/C%23-NETx/WebAPIService/Batch/BatchRequest.cs#L96). Did you set this using the service property?

But this isn't the only way to execute a query using FetchXml. You can also use the [FetchXmlRequest ](https://github.com/microsoft/PowerApps-Samples/blob/master/dataverse/webapi/C%23-NETx/WebAPIService/Messages/FetchXMLRequest.cs) and [FetchXmlResponse ](https://github.com/microsoft/PowerApps-Samples/blob/master/dataverse/webapi/C%23-NETx/WebAPIService/Messages/FetchXMLResponse.cs) classes which would not send the request using $batch. This might simplify troubleshooting.

**Comment by mkalinovTC** [comment]
Hi Jim, thanks for ur response.
I have change the code to use FetchXmlRequest, thanks for the tip.
Regarding the BaseAddress. We haven't explicitly set it as none of examples (except delete) shows it as a need.
As we checked in debugger, BaseAddress is still populated fine even if not set explicitly. But response is still "NotFound" in this case.

**Comment by JimDaly** [comment]
@mkalinovTC 
Can you send a code snippet and a Fiddler trace?

**Comment by mkalinovTC** [comment]
HI Jim, please give me couple of days. It's hard time now. Will do asap.

**Comment by mkalinovTC** [comment]
Hi @JimDaly,
So sorry for delay.
I had a time to restore the old code. Here is the screenshot of Service.BaseAddress property having a proper value:

![BaseAddress](https://user-images.githubusercontent.com/77283662/201131749-d2c39e72-f746-4f3c-a3fe-3449cb2a2827.JPG)

Abd here is the Fiddler with base url lost:
![Fidler](https://user-images.githubusercontent.com/77283662/201132854-75e70d43-bec9-417b-8635-0ed2194cc2a3.JPG)

It ends with error: Not Found

**Comment by JimDaly** [comment]
@mkalinovTC 
I created a branch on the samples repo named `jdaly-master-329-investigation`.
There, I edited the existing Query Data sample, commenting out all except Section 8. See [Line 614](https://github.com/microsoft/PowerApps-Samples/blob/8db5c32436d6f6a80a48c1513f1586cdd4477abd/dataverse/webapi/C%23-NETx/QueryData/Program.cs#L614)

So the code starting a line 645 is:

```
            FetchXmlRequest fetchXmlRequest = new(
                entitySetName:"contacts",
                fetchXml: XDocument.Parse(fetchXmlQuery),
                includeAnnotations: true);

            BatchRequest batchTestRequest = new(serviceBaseAddress: service.BaseAddress) { 
                
                Requests = new List<HttpRequestMessage> { fetchXmlRequest }
            };

            FetchXmlResponse contacts;
            try
            {
                BatchResponse batchResponse = await service.SendAsync<BatchResponse>(batchTestRequest);

                 contacts = batchResponse.HttpResponseMessages.FirstOrDefault().As<FetchXmlResponse>();
            }
            catch (Exception)
            {
                throw;
            }
```

The fiddler trace for this request is:
```
POST https://myorg.api.crm.dynamics.com/api/data/v9.2/$batch HTTP/1.1
Host: myorg.api.crm.dynamics.com
Authorization: Bearer [REDACTED]
User-Agent: WebAPIService/1.0.0.0
OData-MaxVersion: 4.0
OData-Version: 4.0
If-None-Match: null
Accept: application/json
Cookie: ReqClientId=6700e558-0abf-4c6d-b3c4-6caa5a27b533; orgId=883278f5-07af-45eb-a0bc-3fea67caa544; last_commit_time=2022-11-10 17:29:52Z; ARRAffinity=8b225453834dd35d8d480e86b85d1fa57832b4fbcdcd2b207cce7063223b0a8beb29bb4b19df1459d2ea781b605f33064b9fea1f144b525b9d7676625c4ffb5408DAC345408F8C68728851243
Content-Type: multipart/mixed; boundary="batch_34451040-1f67-48ac-8b8f-eae5c95639c0"
Content-Length: 1040

--batch_34451040-1f67-48ac-8b8f-eae5c95639c0
Content-Type: application/http
Content-Transfer-Encoding: binary

GET /api/data/v9.2/contacts?fetchXml=%3Cfetch+mapping%3D%22logical%22+output-format%3D%22xml-platform%22+version%3D%221.0%22+distinct%3D%22false%22%3E%0D%0A++%3Centity+name%3D%22contact%22%3E%0D%0A++++%3Cattribute+name%3D%22fullname%22+%2F%3E%0D%0A++++%3Cattribute+name%3D%22jobtitle%22+%2F%3E%0D%0A++++%3Cattribute+name%3D%22annualincome%22+%2F%3E%0D%0A++++%3Corder+descending%3D%22true%22+attribute%3D%22fullname%22+%2F%3E%0D%0A++++%3Cfilter+type%3D%22and%22%3E%0D%0A++++++%3Ccondition+value%3D%22%25(sample)%25%22+attribute%3D%22fullname%22+operator%3D%22like%22+%2F%3E%0D%0A++++++%3Ccondition+value%3D%22902ba62b-1d61-ed11-9562-000d3a9933c9%22+attribute%3D%22parentcustomerid%22+operator%3D%22eq%22+%2F%3E%0D%0A++++%3C%2Ffilter%3E%0D%0A++%3C%2Fentity%3E%0D%0A%3C%2Ffetch%3E&$count=true HTTP/1.1
Host: myorg.api.crm.dynamics.com
Prefer: odata.include-annotations="*"


--batch_34451040-1f67-48ac-8b8f-eae5c95639c0--
```
If you have cloned the repository, you should be able to select the `jdaly-master-329-investigation` branch. 
Edit the appsettings.json with your settings, and make sure that the `Url` doesn't include any backslash characters.
It should be `https://yourorg.api.crm.dynamics.com`, and not `https://yourorg.api.crm.dynamics.com/`.

```
//Do not check in changes to this file
{
  "Url": "https://yourorg.api.crm.dynamics.com",
  "UserPrincipalName": "you@yourorg.onmicrosoft.com",
  "Password": "yourPassword",
  "Version": "9.2",
  "ClientId": "51f81489-12ee-4a9e-aaae-a2591f45987d",
  "RedirectUri": "app://58145B91-0C36-4500-8554-080854F2AC97",
  "Authority": "https://login.microsoftonline.com/organizations",
  "TimeoutInSeconds": 120,
  "CallerObjectId": "00000000-0000-0000-0000-000000000000", //Empty
  "MaxRetries": 3
}
```
This test doesn't include the Microsoft.Dynamics.CRM.NextXDays function in the fetchXml that you originally reported. Is that still a factor in the Repro?

Can you verify that you get the same behavior with the sample code?
Can you set a breakpoint within the ToMessageContent private method here: [private HttpMessageContent ToMessageContent(HttpRequestMessage request)](https://github.com/microsoft/PowerApps-Samples/blob/8db5c32436d6f6a80a48c1513f1586cdd4477abd/dataverse/webapi/C%23-NETx/WebAPIService/Batch/BatchRequest.cs#L96)

**Comment by mkalinovTC** [comment]
Thanks for the environment, Jim. It helps. I will test once I can.
Regarding Microsoft.Dynamics.CRM.NextXDays. It works ok with fetch but OData4 syntax. 
I had to change query approach to "workaround" this.

**Comment by JimDaly** [comment]
@mkalinovTC 
I haven't heard back from you. Assuming all is working. 
I haven't got any specific actionable item to address in the docs, so closing this.
