### ISSUE TITLE
Component is not displayed until Refresh clicked on command menu

### ISSUE THREAD

**Issue by LozzieDuff** [microsoft/PowerApps-Samples#331]
When the ModelDrivenGrid solution is published and executed in PowerApps, nothing is displayed until Refresh is clicked on the command menu.

Maybe this is by design?

If not, this can be fixed by inserting ...

this.context.parameters.records.refresh();

... at the end of the public init method.

**Comment by phecke** [comment]
@LozzieDuff Are you asking about one of our code samples? If so, which one?

**Comment by LozzieDuff** [comment]
@phecke Hi there, yes, the ModelDrivenGridControl ...

https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/ModelDrivenGridControl

I downloaded and installed it as is (great demonstrator, btw), but it didn't appear to show any data.  Hitting browser refresh didn't help.  Hit the command bar Refresh and whoosh, there it was.  Stepped through the code (I'm a newbie with the JSX, React, PCF frameworks/stacks/whatever(!), more dotnet and vanilla JavaScript experience) but eventually took a punt on adding -- this.context.parameters.records.refresh(); -- at the end of the public init method.  That worked.

Whether it is the right thing to do or if I've missed a bit out of newbie-ness I don't know!

If it is a valid "fix", can I have a go at branching and pull request the "fix" in and all that jazz?  My first contribution - break my Github virginity, so-to-speak!

**Comment by ginow** [comment]
For me the component is loading but data isn't, but when I click on "Refresh" in the command bar it starts showing data. Even clicking on sorting shows the data.

- During page load

![noRecordsFound](https://user-images.githubusercontent.com/15030674/201476576-eb4df9c7-c73e-4cd5-9d46-dcbf0c8d4899.png)

- After clicking "Refresh" or "Sorting"

![image](https://user-images.githubusercontent.com/15030674/201476697-7fc5f606-fd44-4945-9e5d-2c63b56be140.png)

**Comment by LozzieDuff** [comment]
Yep, that's the issue I experienced.

As said, try adding: **this.context.parameters.records.refresh();** -- at the end of the public init method.

**Comment by LozzieDuff** [comment]
Yes that's correct.

**Comment by JimDaly** [comment]
@LozzieDuff 
Thanks. I've created a workitem to review this tutorial with focus on those steps.

3037743
