### ISSUE TITLE
Create Entity Request

### ISSUE THREAD

**Issue by murati** [microsoft/PowerApps-Samples#338]
When I submitted a create entity request, it throws an exception:

Attribute of type AttributeMetadata cannot be created through the SDK. Based on my research it gives me this error because of lookup fields but unfortunately, the SDK does not allow us to set Attributes since it is readonly. 

Any ideas?

**Comment by BetimBeja** [comment]
Hi @murati,
I used LinqPad for a quick test and it created the entity without problems...
![image](https://user-images.githubusercontent.com/11160171/200372149-9b596f61-b72b-49a8-a806-085ec3a681ee.png)


code is from the Microsoft Samples:
```csharp
var _customEntityName = "new_BankAccount";
CreateEntityRequest createrequest = new CreateEntityRequest
{

 //Define the entity
 Entity = new EntityMetadata
 {
  SchemaName = _customEntityName,
  DisplayName = new Label("Bank Account", 1033),
  DisplayCollectionName = new Label("Bank Accounts", 1033),
  Description = new Label("An entity to store information about customer bank accounts", 1033),
  OwnershipType = OwnershipTypes.UserOwned,
  IsActivity = false,

 },

 // Define the primary attribute for the entity
 PrimaryAttribute = new StringAttributeMetadata
 {
  SchemaName = "new_accountname",
  RequiredLevel = new AttributeRequiredLevelManagedProperty(AttributeRequiredLevel.None),
  MaxLength = 100,
  FormatName = StringFormatName.Text,
  DisplayName = new Label("Account Name", 1033),
  Description = new Label("The primary attribute for the Bank Account entity.", 1033)
 }

};
DataverseClient.Execute(createrequest);
Console.WriteLine("The bank account entity has been created.");
```
for reference: [CreateEntityRequest](https://learn.microsoft.com/dotnet/api/microsoft.xrm.sdk.messages.createentityrequest?view=dataverse-sdk-latest&WT.mc_id=DX-MVP-5004767)
To Actually create the `Columns` you need to execute another request: [CreateAttributeRequest](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.messages.createattributerequest?view=dataverse-sdk-latest&WT.mc_id=DX-MVP-5004767)

**Comment by JimDaly** [comment]
@murati 
Sorry for the delay in responding.
If you have an issue with any of our published samples, please raise an issue here.
But we can't provide technical support through this forum.
