### ISSUE TITLE
Step 7 fails

### ISSUE THREAD

**Issue by nunon** [microsoft/PowerApps-Samples#357]
I'm trying to follow the installation tutorial for the power apps components, but on step 7, after running:

msbuild /t:rebuild /restore /p:Configuration=Release

With the message:

C:\Users\nuno_\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.20.3\build\Microsoft.PowerApps.MSBuild.Pcf.targets(64,5): error MSB3073: The command "npm run build -- --noColor --buildMode production --outDir "C:\User
s\nuno_\Documents\CanvasGrid\out\controls" --buildSource MSBuild" exited with code -1. [C:\Users\nuno_\Documents\CanvasGrid\CanvasGrid.pcfproj]
Done Building Project "C:\Users\nuno_\Documents\CanvasGrid\CanvasGrid.pcfproj" (default targets) -- FAILED.

Done Building Project "C:\Users\nuno_\Documents\CanvasGrid\testes\testes.cdsproj" (rebuild target(s)) -- FAILED.

Build FAILED.

"C:\Users\nuno_\Documents\CanvasGrid\testes\testes.cdsproj" (rebuild target) (1:7) ->
"C:\Users\nuno_\Documents\CanvasGrid\CanvasGrid.pcfproj" (default target) (2:7) ->
(PcfBuild target) ->
  C:\Users\nuno_\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.20.3\build\Microsoft.PowerApps.MSBuild.Pcf.targets(64,5): error : [pcf-1065] [Error] ESLint validation error:  [C:\Users\nuno_\Documents\CanvasGrid\Can
vasGrid.pcfproj]
  C:\Users\nuno_\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.20.3\build\Microsoft.PowerApps.MSBuild.Pcf.targets(64,5): error MSB3073: The command "npm run build -- --noColor --buildMode production --outDir "C:\Us
ers\nuno_\Documents\CanvasGrid\out\controls" --buildSource MSBuild" exited with code -1. [C:\Users\nuno_\Documents\CanvasGrid\CanvasGrid.pcfproj]

    0 Warning(s)
    2 Error(s)

**Comment by JimDaly** [comment]
@nunon 
Sorry for the delay in responding.

Our doc feedback system with Github issues works best when you use the button at the bottom of the page. This includes details about what page you have feedback about and routes the issue to the author.

Which page is your feedback regarding?

**Comment by meeple142** [comment]
I'm pretty sure they are talking about https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework
I am having the same problem

**Comment by JoelMTaylor** [comment]
@JimDaly, @meeple142, @nunon, has anyone found a solution? I am getting the same errors.

**Comment by JimDaly** [comment]
@JoelMTaylor 
Which sample or tutorial are you having this issue with?

**Comment by JoelMTaylor** [comment]
I am following the readme at: https://github.com/microsoft/PowerApps-Samples#how-to-run-the-sample-components. I am trying to add the IFrameControl to my canvas app.

**Comment by JimDaly** [comment]
@JoelMTaylor 

Thanks for the clues.

That link doesn't take me to any instructions. It is just the readme for the root of the repo.
I think you must mean this one:
https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework#how-to-run-the-sample-components

There are instructions about using the samples here:
https://learn.microsoft.com/en-us/power-apps/developer/component-framework/use-sample-components 
The README is duplicating this content..

Hmm the instructions are not clear. You can't download individual samples. You could download the repo, but that seems excessive. Probably best to just clone the repo.

Instructions also talk about using the VS 2017 command prompt. That seems out of date. I would recommend you use a terminal with VS Code.

These instructions need work. Sorry to find them in this state.
The instructions seem to be the same as those in the content here:
https://learn.microsoft.com/en-us/power-apps/developer/component-framework/import-custom-controls

I think I will refactor these read-me instructions so that they don't repeat the content about using pac solution.
I will test some of these components to verify that they work.

I recommend you:
1. Clone the repo if you haven't already. (Anytime you download a zip file, you probably need to go to properties and unblock it. that could be the problem if you are downloading the whole repo)
2. Use Visual Studio Code rather than the VS 2017 command prompt if you haven't already.
3. Follow the documentation guidance rather than these README instructions.
Documentation is here: https://learn.microsoft.com/en-us/power-apps/developer/component-framework/import-custom-controls
4. Try some of the other components, like LinearInputControl and see if you have the same issues.

I can't provide technical support. If you need immediate help, please contact technical support. 
But I will test this out and work to get the instructions improved and verify that the steps we document are correct.

**Comment by JoelMTaylor** [comment]
@JimDaly, thank you for detailed instructions. I will try them and report back.

**Comment by JoelMTaylor** [comment]
@JimDaly, I tried to follow the steps in the other location and your recommendations. However, I didn't have more success. I also tried with LinearInputControl, and I had the same issues. 

I don't know if you are interested, but below is the error when running step four:
```
PS D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution> & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" /t:build /restore
MSBuild version 17.5.1+f6fdcf537 for .NET Framework
Build started 23/03/23 15:56:55.
Included response file: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.rsp

Project "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\Solution.cdsproj" on node 1 (Restore target(s)).
_GetAllRestoreProjectPathItems:
  Determining projects to restore...
Restore:
  X.509 certificate chain validation will use the default trust store selected by .NET.
  X.509 certificate chain validation will use the default trust store selected by .NET.
  Restoring packages for D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\Solution.cdsproj...
  Restoring packages for D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\LinearInputControl.pcfproj...
    GET https://api.nuget.org/v3-flatcontainer/microsoft.powerapps.msbuild.solution/index.json
    GET https://api.nuget.org/v3-flatcontainer/microsoft.powerapps.msbuild.pcf/index.json
    OK https://api.nuget.org/v3-flatcontainer/microsoft.powerapps.msbuild.solution/index.json 339ms
    OK https://api.nuget.org/v3-flatcontainer/microsoft.powerapps.msbuild.pcf/index.json 400ms
  Generating MSBuild file D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\obj\LinearInputControl.pcfproj.nuget.g.props.
  Generating MSBuild file D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\obj\LinearInputControl.pcfproj.nuget.g.targets.
  Writing assets file to disk. Path: D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\obj\project.assets.json
  Restored D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\LinearInputControl.pcfproj (in 1.12 sec).
  Generating MSBuild file D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\obj\Solution.cdsproj.nuget.g.props.
  Generating MSBuild file D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\obj\Solution.cdsproj.nuget.g.targets.
  Writing assets file to disk. Path: D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\obj\project.assets.json
  Restored D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\Solution.cdsproj (in 1.21 sec).

  NuGet Config files used:
      C:\Users\joel\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
Done Building Project "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\Solution.cdsproj" (Restore target(s)).

Project "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\Solution.cdsproj" on node 1 (build target(s)).
PrepareForBuild:
  Creating directory "bin\Debug\".
  Creating directory "obj\Debug\".
Project "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\Solution.cdsproj" (1:7) is building "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputCon
trol\LinearInputControl.pcfproj" (2:6) on node 1 (default targets).
PrepareForBuild:
  Creating directory "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\out\controls\".
  Creating directory "obj\Debug\".
PcfBuild:
  npm run build -- --noColor --buildMode development --outDir "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\out\controls" --buildSource MSBuild
  
  > pcf-project@1.0.0 build
  > pcf-scripts build --noColor --buildMode development --outDir D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\out\controls --buildSource MSBuild

  'pcf-scripts' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\joel\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.21.13\build\Microsoft.PowerApps.MSBuild.Pcf.targets(64,5): error MSB3073: The command "npm run build -- --noColor --buildMode development 
--outDir "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\out\controls" --buildSource MSBuild" exited with code 1. [D:\Projects\GitHub\PowerApps Samples\component-framework\L 
inearInputControl\LinearInputControl.pcfproj]
Done Building Project "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\LinearInputControl.pcfproj" (default targets) -- FAILED.

Done Building Project "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\Solution.cdsproj" (build target(s)) -- FAILED.


Build FAILED.

"D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\Solution\Solution.cdsproj" (build target) (1:7) ->
"D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\LinearInputControl.pcfproj" (default target) (2:6) ->
(PcfBuild target) ->
  C:\Users\joel\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.21.13\build\Microsoft.PowerApps.MSBuild.Pcf.targets(64,5): error MSB3073: The command "npm run build -- --noColor --buildMode developmen 
t --outDir "D:\Projects\GitHub\PowerApps Samples\component-framework\LinearInputControl\out\controls" --buildSource MSBuild" exited with code 1. [D:\Projects\GitHub\PowerApps Samples\component-framework 
\LinearInputControl\LinearInputControl.pcfproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.70
```

**Comment by JimDaly** [comment]
@JoelMTaylor 

Based on what I found online and another customers response to https://github.com/MicrosoftDocs/powerapps-docs/issues/756

I think the issue could be that you must run `npm install` for the control project first.
If you were creating the project, you would have done that. But in this case, seems people are working with projects in our sample repo that they didn't create. Running `npm install` could be what is necessary...?

I haven't tested this yet. If it works for you please let me know.

If it is necessary, we need to update the docs to call this out.

**Comment by JoelMTaylor** [comment]
@JimDaly, I tried that, but had the same issue. 

I am going to document what I am doing. I suspect that I am doing something wrong. There are some times that the steps say to do something in a particular location, for example "[go into your solution project directory](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/import-custom-controls#:~:text=go%20into%20your%20solution%20project%20directory)". I feel that I might make a mistake here and run the cmdlet in the wrong location. (I apologise that these might be stupid and uneducated mistakes.)

I am going to try the [steps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/import-custom-controls) again with the MultiSelectOptionSetControl component. I have cloned the [repository](https://github.com/microsoft/PowerApps-Samples), I have it in VS Code and I am using PS7 (I have previously tried with PS5). The repository is saved to `D:\Projects\GitHub\PowerApps Samples`. My terminal is open to `D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl`. Since the folder tree is always the same, I will represent `D:\Projects\GitHub\PowerApps Samples\component-framework` as `...`.

Below are the steps that I complete, along with the results.

1. `PS ...\MultiSelectOptionSetControl> npm install`
Result:
```
added 627 packages, and audited 628 packages in 38s
59 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
```
2. `PS ...\MultiSelectOptionSetControl> mkdir Solution`
Result:
```
Directory: D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            23/03/23    17:52                Solution
```
3. `PS ...\MultiSelectOptionSetControl> cd Solution`
4. `PS ...\MultiSelectOptionSetControl\Solution> pac solution init --publisher-name JoelTaylor --publisher-prefix JT`
Result:
```
Dataverse solution project with name 'Solution' created successfully in: 'D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution'
Dataverse solution files were successfully created for this project in the sub-directory Other, using solution name Solution, publisher name JoelTaylor, and customization prefix jt.
Please verify the publisher information and solution name found in the Solution.xml file.
```
5. `PS ...\MultiSelectOptionSetControl\Solution> pac solution add-reference --path "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\"`
Result:
```
Project reference successfully added to Dataverse solution project.
```
6. `PS ...\MultiSelectOptionSetControl\Solution> msBuild /t:build /restore`
Please note: I included this here for completeness. I also ran this separately in VS Build Tools and had the same result as step 7 below. Result:
```
msBuild: The term 'msBuild' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
7. `PS ...\MultiSelectOptionSetControl\Solution> & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" /t:build /restore`
Normally, I receive two errors (sometimes only one). I am not sure why I received three this time (the steps were the same as previous times). Result:
```
MSBuild version 17.5.1+f6fdcf537 for .NET Framework
Build started 23/03/23 17:59:18.
Included response file: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.rsp

Project "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\Solution.cdsproj" on node 1 (Restore target(s)).
_GetAllRestoreProjectPathItems:
  Determining projects to restore...
Restore:
  X.509 certificate chain validation will use the default trust store selected by .NET.
  X.509 certificate chain validation will use the default trust store selected by .NET.
  Restoring packages for D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj...
  Restoring packages for D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\Solution.cdsproj...
    GET https://api.nuget.org/v3-flatcontainer/microsoft.powerapps.msbuild.solution/index.json
    GET https://api.nuget.org/v3-flatcontainer/microsoft.powerapps.msbuild.pcf/index.json
    OK https://api.nuget.org/v3-flatcontainer/microsoft.powerapps.msbuild.solution/index.json 337ms
    OK https://api.nuget.org/v3-flatcontainer/microsoft.powerapps.msbuild.pcf/index.json 407ms
  Generating MSBuild file D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\obj\MultiSelectOptionSetControl.pcfproj.nuget.g.props.
  Generating MSBuild file D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\obj\MultiSelectOptionSetControl.pcfproj.nuget.g.targets.
  Writing assets file to disk. Path: D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\obj\project.assets.json
  Restored D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj (in 1.17 sec).
  Generating MSBuild file D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\obj\Solution.cdsproj.nuget.g.props.
  Generating MSBuild file D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\obj\Solution.cdsproj.nuget.g.targets.
  Writing assets file to disk. Path: D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\obj\project.assets.json
  Restored D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\Solution.cdsproj (in 1.28 sec).

  NuGet Config files used:
      C:\Users\joel\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
Done Building Project "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\Solution.cdsproj" (Restore target(s)).

Project "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\Solution.cdsproj" on node 1 (build target(s)).
PrepareForBuild:
  Creating directory "bin\Debug\".
  Creating directory "obj\Debug\".
Project "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\Solution.cdsproj" (1:7) is building "D:\Projects\GitHub\PowerApps Samples\component-framework\Multi
SelectOptionSetControl\MultiSelectOptionSetControl.pcfproj" (2:6) on node 1 (default targets).
PrepareForBuild:
  Creating directory "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\out\controls\".
  Creating directory "obj\Debug\".
PcfBuild:
  npm run build -- --noColor --buildMode development --outDir "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\out\controls" --buildSource MSBuild
  
  > pcf-project@1.0.0 build
  > pcf-scripts build --noColor --buildMode development --outDir D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\out\controls --buildSource MSBuild

  [5:59:31 pm] [build]  Initializing...
  [5:59:31 pm] [build]  Validating manifest...
  [5:59:31 pm] [build]  Validating control...
  [5:59:33 pm] [build]  Running ESLint...
C:\Users\joel\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.21.13\build\Microsoft.PowerApps.MSBuild.Pcf.targets(64,5): error : [pcf-scripts] [Error] encountered unexpected error: [D:\Projects\GitHub
\PowerApps Samples\component-framework\MultiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj]
EXEC : error : Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Cannot find module '@typescript-eslint/eslint-plugin' [D:\Projects\GitHub\PowerApps Samples\component-framework\Mu
ltiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj]
  Require stack:
  - D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\__placeholder__.js
  Referenced from: D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\.eslintrc.json
C:\Users\joel\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.21.13\build\Microsoft.PowerApps.MSBuild.Pcf.targets(64,5): error MSB3073: The command "npm run build -- --noColor --buildMode development 
--outDir "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\out\controls" --buildSource MSBuild" exited with code 1. [D:\Projects\GitHub\PowerApps Samples\component-fr 
amework\MultiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj]
Done Building Project "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj" (default targets) -- FAILED.

Done Building Project "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\Solution.cdsproj" (build target(s)) -- FAILED.


Build FAILED.

"D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\Solution\Solution.cdsproj" (build target) (1:7) ->
"D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj" (default target) (2:6) ->
(PcfBuild target) ->
  C:\Users\joel\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.21.13\build\Microsoft.PowerApps.MSBuild.Pcf.targets(64,5): error : [pcf-scripts] [Error] encountered unexpected error: [D:\Projects\GitH 
ub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj]
  EXEC : error : Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Cannot find module '@typescript-eslint/eslint-plugin' [D:\Projects\GitHub\PowerApps Samples\component-framework\ 
MultiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj]
  C:\Users\joel\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.21.13\build\Microsoft.PowerApps.MSBuild.Pcf.targets(64,5): error MSB3073: The command "npm run build -- --noColor --buildMode developmen 
t --outDir "D:\Projects\GitHub\PowerApps Samples\component-framework\MultiSelectOptionSetControl\out\controls" --buildSource MSBuild" exited with code 1. [D:\Projects\GitHub\PowerApps Samples\component- 
framework\MultiSelectOptionSetControl\MultiSelectOptionSetControl.pcfproj]

    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:16.15
```

**Comment by rcjohnson113** [comment]
Getting the same exact issue, any update on resolution?

**Comment by JimDaly** [comment]
With guidance from the dev team, I've updated all the `.eslintrc.json` and `package.json` files to match the current files generated with `pac pcf init`.

I've also re-written and tested the instructions found in the [README](https://github.com/microsoft/PowerApps-Samples/blob/master/component-framework/README.md), and included the example output of the steps for successfully generating zip files for the samples.

@rcjohnson113, @JoelMTaylor, @meeple142, and @nunon 
I'm closing this, but please verify that these instructions work for you now. 
Thanks for raising this and your patience in getting it resolved.
