### ISSUE TITLE
Using the wrong type on the left

### ISSUE THREAD

**Issue by nkatz01** [microsoft/PowerApps-Samples#360]
Should be AuditDetails instead of AttributeAuditDetail

https://github.com/microsoft/PowerApps-Samples/blob/60fa0748caf398c1af5b7582e643e219554f996f/dataverse/orgsvc/C%23/AuditEntityData/AuditEntityData/SampleProgram.cs#L66

P.S. Thanks a lot for the code! Very helpful!

**Comment by phecke** [comment]
@nkatz01 Corrected. Thanks.
