### ISSUE TITLE
Request Body must contain 'client_secret'

### ISSUE THREAD

**Issue by avawise001** [microsoft/PowerApps-Samples#362]
When using the sample code to interact with an instance of Dynamics 365 for sales; however I receive an error the call to AcquireTokenInteractive in app.cs

I complete the browser based authentication; received an authentication complete message; then receive the following error message.

Microsoft.Identity.Client.MsalServiceException: 'A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

There is no obvious way of including my client_secret in the code.  Any thoughts would be gratefully received

**Comment by phecke** [comment]
@avawise001 What code sample are you trying?

**Comment by avawise001** [comment]
dataverse / webapi / c#-netx / querydata

The exception occurs in the GetToken method of App.cs.  at the following line:

`result = await app.AcquireTokenInteractive(scopes).ExecuteAsync();`

**Comment by JimDaly** [comment]
@avawise001 
The `GetToken` method in [App.cs](https://github.com/microsoft/PowerApps-Samples/blob/master/dataverse/webapi/C%23-NETx/App.cs) is used to provide an access token for the Web API samples.

It should work if:
1. You are using the UPN for the account that you use to access Dataverse. This should not be a security principal account, but your actual user credentials.
2. It will work best if you provide your password in the [appsettings.json](https://github.com/microsoft/PowerApps-Samples/blob/master/dataverse/webapi/C%23-NETx/appsettings.json) file. You haven't mentioned if you tried this or not.
3. You must not change the `ClientId` or `RedirectUri` values.

If these three points are true, it should work. There should be no need to include a client assertion or client secret.
If you are trying to do something else, please advise what your goal is and what you are doing differently.

**Comment by JimDaly** [comment]
Also, see [Desktop app that calls web APIs: Acquire a token](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet) which outlines all the different ways to acquire a token using a desktop app.

These samples use [Username and Password](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token-username-password?tabs=dotnet), which isn't a recommended pattern. Within this topic you can see a reference to this error:

```
   // ------------------------------------------------------------------------
   // AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.
   // Explanation: this can happen if your application was not registered as a public client application in Azure AD
   // Mitigation: in the Azure portal, edit the manifest for your application and set the `allowPublicClient` to `true`
   // ------------------------------------------------------------------------
```

Since the clientid used by default with these samples is a public client application, I suspect that you are using a different clientid value than the one provided. Please confirm.

**Comment by avawise001** [comment]
Thanks for your help - all working now - I had replaced the `ClientId` value with that of an App Registration in Azure AD in error.  A silly error

However it is worth noting that the sample only works for me when the `RedirectUri` value is set to http://localhost.  The suggested value app://51f81489... creates the 'Only loopback redirect uri is supported ...' exception

Thanks again
