### ISSUE TITLE
Path collision when cloning the repo on windows

### ISSUE THREAD

**Issue by TclasenITVT** [microsoft/PowerApps-Samples#42]
Hello Microsoft,

when I cloned this repository I got following message:

> warning: the following paths have collided (e.g. case-sensitive paths
> on a case-insensitive filesystem) and only one from the same
> colliding group is in the working tree:
>
>   'cds/orgsvc/C#/ExecuteMultipleRequests/ExecuteMultipleRequests.sln'
>   'cds/orgsvc/C#/ExecutemultipleRequests/ExecutemultipleRequests.sln'
>   'cds/orgsvc/C#/ExecuteMultipleRequests/ExecuteMultipleRequests/ExecuteMultipleRequests.csproj'
>   'cds/orgsvc/C#/ExecutemultipleRequests/ExecutemultipleRequests/ExecutemultipleRequests.csproj'
>   'cds/orgsvc/C#/ExecuteMultipleRequests/ExecuteMultipleRequests/packages.config'
>   'cds/orgsvc/C#/ExecutemultipleRequests/ExecutemultipleRequests/packages.config'
>   'cds/orgsvc/C#/ExecuteMultipleRequests/ExecuteMultipleRequests/Properties/AssemblyInfo.cs'
>   'cds/orgsvc/C#/ExecutemultipleRequests/ExecutemultipleRequests/Properties/AssemblyInfo.cs'
>   'cds/orgsvc/C#/ExecuteMultipleRequests/ExecuteMultipleRequests/SampleMethod.cs'
>   'cds/orgsvc/C#/ExecutemultipleRequests/ExecutemultipleRequests/SampleMethod.cs'
>   'cds/orgsvc/C#/ExecuteMultipleRequests/ExecuteMultipleRequests/SampleProgram.cs'
>   'cds/orgsvc/C#/ExecutemultipleRequests/ExecutemultipleRequests/SampleProgram.cs'
>   'cds/orgsvc/C#/RetrieveFieldPermission/RetrieveFieldPermission/SampleMEthod.cs'
>   'cds/orgsvc/C#/RetrieveFieldPermission/RetrieveFieldPermission/SampleMethod.cs'

Please review these files and clean up your repository.

**Comment by Nkrb** [comment]
@TclasenITVT Thanks for the feedback. We have updated the samples and pushed to live. Closing the issue.
