### ISSUE TITLE
PowerApps Build Tools Sample for OAuth/Certificate based Connection

### ISSUE THREAD

**Issue by TclasenITVT** [microsoft/PowerApps-Samples#43]
Hello Microsoft,

I'm just working through your PowerApps Build Tools Sample and I was trying to get it working using a non-interactive user( using AAD Appregistration) for interaction with Dynamics 365 but I cant get it to work.

My Generic Service Connection is filled out like this:
Name: "Test Connection"
Server Url: "https://crmName.crm4.dynamics.com"
Username: clientId from AppRegistration
Password: clientSecret from AppRegistration

It works just fine using my own username and password but with MFA enabled having a non-interactive user would be potentially the safer bet. Hopefully there is a solution for this.

**Comment by TclasenITVT** [comment]
Would have been nice if microsoft thought of getting this out before choosing to force mfa on all partners 😉 or maybe to just cooperate with Wael Hamze on the existing [Dynamics 365 Build Tools](https://github.com/WaelHamze/dyn365-ce-vsts-tasks) instead...
Anyway thanks for finally pushing for a CI/CD Story for Dynamics 365 PowerApps and CRM it was desperatly needed! Is there a public roadmap with more details of whats to come?

**Comment by Lukis** [comment]
@TclasenITVT - Wael's project has the non interactive login feature in a few branches. I worked with another contributor on the feature request. It might even be merged by now. I'd recommend looking into it over at his GitHub project.

**Comment by Nkrb** [comment]
@TclasenITVT Thanks for the feedback. Closing the issue. Please do reopen the issue if you think the information provided is insufficient.
