### ISSUE TITLE
Automated CDS Env + Data Build?

### ISSUE THREAD

**Issue by SeaDude** [microsoft/PowerApps-Samples#44]
Hello,
The [`README.md` listed here](https://github.com/microsoft/PowerApps-Samples/blob/master/ai-builder/labs/README.md) says to `Follow the instructions in the Automated Lab Environment folder to build and run the tool which will create a trial Common Data Service organization with the data already uploaded.` 
**I can't find this folder in the repo.** 
Any details?
Thank you

**Comment by SeaDude** [comment]
ANy ideas on this?

**Comment by Dean-Haas** [comment]
The automated lab component was removed prior to the lab being released. The readme should have been updated to remove that reference. Thanks for pointing this out.

**Comment by KumarVivek** [comment]
@SeaDude The readme was updated to remove the outdated instructions. Thanks for reporting the issue.
