### ISSUE TITLE
PowerApps grid control customizer column filters problem

### ISSUE THREAD

**Issue by mianfriH** [microsoft/PowerApps-Samples#452]
Hello everyone, I am having a problem with the controlcustomizer and the column filters. I explain... When I filter some of the columns, sometimes, many times, the funnel icon and the option to clean filters, disappear from the column header. And the times that they don't disappear, when I clean filters, all the results are not shown again. In other words, it is as if I only get the filter the first time and the grid remains with that filter until I refresh the page.

Any help on this would be very welcome. This problem is driving me crazy and is going to force me to remove a control that has taken me many hours of development.

Thanks.

_Originally posted by @mianfriH in https://github.com/microsoft/PowerApps-Samples/issues/381#issuecomment-1608931511_

**Comment by brasov2de** [comment]
Hi @mianfriH , 

What type of column have you implemented with the customizer control?
Does this happen an all columns? Even the ones you don't change with the customizer control?

**Comment by mianfriH** [comment]
hi. Some types of columns, lookup, persona, two options and optionsset. The control are customizing around 9 or 10 columns in diferents grids in diferent entities.
Yes, this behaviour are in all columns of the grid, not only the customized columns.

I'm refering to the column filter, but when the problem occurs, it's affecting to de "Edit filter funcionality" When i clean the filters, nothing nothing happens. The appliend filters persist until the page reload.

Do you think that the customization of a lot of column in the same grid, could be the problem?

I am really saddened by this behaviour, because it will throw away many hours of cutomisation work.

**Comment by brasov2de** [comment]
On my environment I can reproduce that:
 - the issue happens also when there is no customizer registered, so standard Power Apps
 - The issue happens only for some filter criteria:
     - it works on string columns for every filter criteria
     - for columns like Optionset, boolean, lookup, the condition like "Contains", "Does not contain", "Begins with", "Does not begin with", "Ends with", "Does not end with" will filter the data, but when we use "Clear filter" after that, the data stays filtered (and the option"clear filter" dissapears. Sometimes we can use the "Edit filters" near the search box to remove the condition, sometimes that also doesn't work .

**Comment by JimDaly** [comment]
@mianfriH & @brasov2de 

This is a forum for issues related to the sample code stored in this repo.
Is there an issue with one of the samples?

This issue is already a couple months old, so I'm going to close it with the expectation that you have moved on to other things.
If there is something that we can address in the sample code, please comment.
