### ISSUE TITLE
Path too long on extraction

### ISSUE THREAD

**Issue by rcjohnson113** [microsoft/PowerApps-Samples#453]
Might want to tell people you have to extract it only on a drive direct path, you cannot have any other folders... Kind of crazy this wasn't thought about when building a huge tree like structure of folders.

![image](https://github.com/microsoft/PowerApps-Samples/assets/6878307/4897b9dd-afed-4b97-9337-4744858c0fd8)

**Comment by phecke** [comment]
@rcjohnson113 Please let us know what code sample (folder path) you are talking about.

**Comment by phecke** [comment]
@rcjohnson113 No response, closing this issue. Feel free to open a new issue with the requested information.
