### ISSUE TITLE
How do we use ExecuteTransactionRequest to create related records in a database transaction?

### ISSUE THREAD

**Issue by jansonjc** [microsoft/PowerApps-Samples#472]
Creating related records is possible in Web Api but we could not find how this can be achieved in Organization Service (using the .NET library). 

In Web Api, [Referencing requests in a Change Set](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/execute-batch-operations-using-web-api#reference-uris-in-an-operation) can be used to achieve this. 

Is there a way the same can be achieved in Organization Service ([ExecuteTransactionRequest](https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.messages.executetransactionrequest))? We could not find anything in documentation or sample code.

**Comment by phecke** [comment]
@jansonjc We do not provide technical support here. However, perhaps this sample is what you are looking for: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/samples/create-update-records-with-related-records
