### ISSUE TITLE
Eslint no-empty-interface error when building DataSetGrid component.

### ISSUE THREAD

**Issue by nstratton-srx** [microsoft/PowerApps-Samples#477]
I cloned the repo today and followed the component-framework readme.

When I tried 
msbuild /t:rebuild /restore /p:Configuration=Release

it failed with the following error:
```
C:\Projects\Demos\PowerApps-Samples\PowerApps-Samples\component-framework\DataSetGrid\DataSetGrid\generated\ManifestT
  ypes.d.ts
    9:18  error  An empty interface is equivalent to `{}`  @typescript-eslint/no-empty-interface
```
ManifestTypes.d.ts 
Line 9
```
export interface IOutputs {
}
```
So it makes sense but it doesn't compile.

I tried adding a "no-empty-interface": "off" rule to the .eslintrc.json file but it didn't ignore the error.

VS Code 1.81.1
MSBuild version 17.6.3+07e294721 for .NET Framework 17.6.3.22601

**Comment by JimDaly** [comment]
@nstratton-srx 
Thanks for reporting this.

I was able to repro and I believe I've addressed this with this PR: #484 

I think you need to use this rule to suppress the error: `"@typescript-eslint/no-empty-interface": "off"`

Please try it again.
