### ISSUE TITLE
Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.8.16603, Culture=neutral, or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by DavidPaf** [microsoft/PowerApps-Samples#478]
I am using Windows 10 and face this issue on debugging: "Could not load file or assembly"  file after downloading the PowerApps Sample folder.

Cannot restore negut package: 

path\PowerApps-Samples-master\PowerApps-Samples-master\dataverse\orgsvc\C#\ConnectionEarlyBound\packages\System.Security.Cryptography.X509Certificates.4.3.2\runtimes/unix/lib/netstandard1.6/System.Security.Cryptography.X509Certificates.dll'.. Please see Error List window for detailed warnings and errors.				

Can you provide details in Setup steps to make sure all references are loaded?

**Comment by phecke** [comment]
@DavidPaf Try updating the NuGet packages to the latest versions and re-building.

**Comment by phecke** [comment]
@DavidPaf If you are still having trouble, file another issue.
