### ISSUE TITLE
PowerApps Build Tools: [error]CanvasApp import: FAILURE: One or more errors occurred.

### ISSUE THREAD

**Issue by francisco-ltech** [microsoft/PowerApps-Samples#49]
Hi,

I believe canvas app are also supported right?

I have followed your tutorial, the "export" pipeline works I can see the app in source control. However, the "build" pipeline fails with not a very helpful error at the PowerApps Import Solution task. Any hints will really be appreciated. Many thanks.

<img width="587" alt="Screenshot 2019-09-26 at 16 38 09" src="https://user-images.githubusercontent.com/29372459/65703263-66fe0200-e07c-11e9-8ba6-09de420a0575.png">

**Comment by Nkrb** [comment]
@francisco-ltech Can you let us know for what sample you are facing this issue.

**Comment by francisco-ltech** [comment]
Hi,

Same app as in the [other ticket](https://github.com/microsoft/PowerApps-Samples/issues/50), also attached here.

[deployme_20190926161705.zip](https://github.com/microsoft/PowerApps-Samples/files/3674574/deployme_20190926161705.zip)

**Comment by Dean-Haas** [comment]
Can you point me to the tutorial you were following?

**Comment by francisco-ltech** [comment]
This one (the lab exercise)

https://github.com/microsoft/PowerApps-Samples/tree/master/azure/build-tools#powerapps_build-tools_labzip

**Comment by mikkelsen2000** [comment]
Couple of questions: can you import the solution manually? (through solutions -> Import solution)? Can you also pls. share the detailed log (under 'variables' in the pipeline you can set debug = true

Thanks
