### ISSUE TITLE
The term 'Join-String' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by chuckstones** [microsoft/PowerApps-Samples#511]
Following error  message is received when attempting to add permission scopes to Microsoft Graph through the ManagePermissionsGrant.ps1 script: 

ApplicationName AppId                               
--------------- -----                               
Microsoft Graph 00000003-0000-0000-c000-000000000000

Join-String : The term 'Join-String' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At C:\Users\________\Downloads\ManagePermissionGrant.ps1:227 char:35
+ $joinedScopes = $selectedScopes | Join-String -Property {$_.Value} -S ...
+                                   ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Join-String:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

The same error is received if attempting to add one permission scope or multiple. 

I am attempting to install the Microsoft Power Platform COE "CenterofExcellenceCoreComponents_4.17_managed.zip" and am unable to due to not being able to create a connection for the HTTP with Azure AD (HTTP with MS Entra) connection reference.  

Reference link: https://learn.microsoft.com/en-gb/connectors/webcontentsv2/#authorize-the-connector-to-act-on-behalf-of-a-signed-in-user

![Entra connection error](https://github.com/microsoft/PowerApps-Samples/assets/153500834/9236d6f6-8279-423e-b218-59b2c64a6d38)

**Comment by martincyr** [comment]
Join-String was introduced with PowerShell 6.2, so my guess is that the script was run with a PowerShell older than 6.2.
#514 should fix that.

**Comment by bhaarathms** [comment]
[PowerShell version 7](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3) or later needs to be installed to run this script.

**Comment by chuckstones** [comment]
Urgh, I'm so sorry guys. You're a absolutely correct, I had v7 installed but it's running side by side with the previous installation, so my shortcut was loading v5.
