### ISSUE TITLE
not able to connect to powerapps env

### ISSUE THREAD

**Issue by akshatakalp** [microsoft/PowerApps-Samples#518]
# Login using PowerApps credentials and register a model with AI Builder
from aibuilder.core.environment import Environment
from aibuilder.models.constants import ModelClientResponseStatus

env = Environment.get(environment_name=aib_environment)

response = env.register_model(model_name=aib_model_name, connection=service, override=True)

if response != ModelClientResponseStatus.success:
    raise Exception('Model registration failed')

print(f"Registered AI Builder model {aib_model_name}")

**Comment by akshatakalp** [comment]
can anyone help me with this.

**Comment by phecke** [comment]
@akshatakalp We do not handle support issues here. Try contact MS Support or post your question in the forums.
