### ISSUE TITLE
Sample doesn't appear to do anything

### ISSUE THREAD

**Issue by JimDaly** [microsoft/PowerApps-Samples#52]
Looking at [Sample: Retrieve email attachments for an email template](https://github.com/microsoft/PowerApps-Samples/blob/master/cds/orgsvc/C%23/RetrieveEmailAttach/RetrieveEmailAttach/SampleProgram.cs)

There doesn't appear to be any code in the Demonstrate section

**Comment by Nkrb** [comment]
@JimDaly Thanks for the feedback. I have added the missing code and pushed it to live. Closing the issue.
