### ISSUE TITLE
ESLint Validation Error - Unexpected Empty Constructor

### ISSUE THREAD

**Issue by tfwoa** [microsoft/PowerApps-Samples#531]
Hopefully this is the right place to add this as it's possible this is down to user error.

I'm following the readme to the letter and getting various errors at step 9 after running.

Is this my setup or could there be a problem with the project?

`msbuild /t:rebuild /restore /p:Configuration=Release`

`Build FAILED.

"C:\PowerApps-Samples-master\component-framework\PowerAppsGridCustomizerControl\PAGridCustomizerControlSolution\PAGridCustomizerControlSolution.cdsproj" (d
efault target) (1) ->
"C:\PowerApps-Samples-master\component-framework\PowerAppsGridCustomizerControl\PowerAppsGridCustomizerControl.pcfproj" (default target) (2:2) ->
(PcfBuild target) ->
  C:\Users\[REDACTED]\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.30.2\build\Microsoft.PowerApps.MSBuild.Pcf.targets(100,5): error : [pcf-1065] [Er
ror] ESLint validation error:  [C:\PowerApps-Samples-master\component-framework\PowerAppsGridCustomizerControl\PowerAppsGridCustomizerControl.pcfproj]
  C:\Users\[REDACTED]\.nuget\packages\microsoft.powerapps.msbuild.pcf\1.30.2\build\Microsoft.PowerApps.MSBuild.Pcf.targets(100,5): error MSB3073: The com
mand "npm run build -- --noColor --buildMode development --outDir "C:\PowerApps-Samples-master\component-framework\PowerAppsGridCustomizerControl\out\contr
ols" --buildSource MSBuild" exited with code -1. [C:\PowerApps-Samples-master\component-framework\PowerAppsGridCustomizerControl\PowerAppsGridCustomizerCon
trol.pcfproj]`

**Comment by torbenpedersen** [comment]
Same experience here following the README.  Step 9 of the IncrementControl has the following command that fails:

`IncrementControlSolution>msbuild /t:rebuild /restore /p:Configuration=Release`


```
npm run clean -- --noColor --buildMode production --outDir "C:\PowerApps-Samples\component- framework\IncrementControl\out\controls" --buildSource MSBuild

> pcf-project@1.0.0 clean
> pcf-scripts clean --noColor --buildMode production --outDir C:\PowerApps-Samples\component-framework\IncrementControl\out\controls --buildSource MSBuild


'pcf-scripts' is not recognized as an internal or external command,
operable program or batch file.'
```

**Comment by torbenpedersen** [comment]
I found the issue on my side was missing packages as they had failed due to a proxy certificate from Zscaler.  If using Zscaler, these commands helped npm get access to the registry:

npm config set proxy http://gateway.zscaler.net:80
npm config set https-proxy http://gateway.zscaler.net:80
npm config set strict-ssl false

**Comment by tfwoa** [comment]
Thanks for the input @torbenpedersen.
We're not using zscaler so I don't think that's part of the issue.

I've looked at the log and dug into the ESLint error. It was something like 'unexpected empty constructuor' in the Index.ts file.

```
 /**
  * Empty constructor.
  */
 constructor() { }
```
I commented out the last line of this block and retried the commands in step 9.

```
/**
  * Empty constructor.
  */
 //constructor() { }
```
Now the build works successfully, and I've imported it into our environment. Is this a valid fix? 

However, the control is not available to add to an entity according to the steps outlined here (it doesn't appear in the list under 'add a control'). What could cause this?

This is on the PowerAppsGridCustomizerControl sample.

**Comment by brasov2de** [comment]
Hi @tfwoa , 
The PowerAppsGrid customizer control cannot be chosem from a list of controls. 
You would use the Power Apps Grid as a control, and define the name of the customizer control as a parameter for the Power Apps Grid. 
I have a blog about this, maybe it helps : https://dianabirkelbach.wordpress.com/2022/07/27/power-apps-grid-control-first-glimpse-to-the-cell-renderer-and-editors/

**Comment by tfwoa** [comment]
Thanks @brasov2de - that helps a lot! Now to add some customisations relevant to our environment so I can check this is working...
