### ISSUE TITLE
Two-way listener is implemented using WindowsAzure.ServiceBus package which is deprecated

### ISSUE THREAD

**Issue by shrutippatil** [microsoft/PowerApps-Samples#544]
Two-way listener is implemented using WindowsAzure.ServiceBus package which is deprecated. Also internally it has dependency on 'Microsoft.Azure.Services.AppAuthentication' which is also deprecated. 

To use Azure service bus, suggested nuget package is  -'Azure.Messaging.ServiceBus,' 
Is there any sample code of 'Two-way listener ' using Azure.Messaging.ServiceBus.

**Comment by phecke** [comment]
@shrutippatil I was not aware of the deprecation. There are no samples in this repo at this time that have been updated to the suggested Azure package. I will create a work item for this, but I do not have a timeframe for its completion.

Thanks for letting us know.

**Comment by phecke** [comment]
Note that you can still use the sample code as is. The WindowsAzure.ServiceBus package will continue to receive updates until 9/30/2026. We will have the sample updated long before then.

**Comment by phecke** [comment]
@shrutippatil I have added this issue to the work item so that we can notify you when the sample is updated.
