### ISSUE TITLE
Sample apps terminate with error finding 'Microsoft.IdentityModel.Clients.ActiveDirectory version=3.19.8.16603

### ISSUE THREAD

**Issue by elitkarthik** [microsoft/PowerApps-Samples#565]
Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.8.16603, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by JimDaly** [comment]
@elitkarthik 
Can you identify which specific sample has this issue?

We accepted some dependabot updates to the Microsoft.IdentityClient libraries recently. It might solve this problem.

**Comment by phecke** [comment]
@elitkarthik File a new issue if you are still having trouble. Closing.
