### ISSUE TITLE
CDS GenerateEntityDiagram Microsoft.Office.Interop.Visio 

### ISSUE THREAD

**Issue by gregdegruy** [microsoft/PowerApps-Samples#57]
Where can one pull down this `Microsoft.Office.Interop.Visio` package? Need this to run the sample, all other packages restore successfully on my machine.

Can not find the `Microsoft.Office.Interop.Visio` package through nuget.

**Comment by MattB-msft** [comment]
That is a com lib,  you have to have Visio installed and link the current version to your project.

________________________________

**Comment by Nkrb** [comment]
@MattB-msft  Thank you for the response. Closing the issue.
