### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by bennyboy23** [microsoft/PowerApps-Samples#58]
Hi,
This lab https://github.com/microsoft/PowerApps-Samples/tree/master/azure/build-tools and the documentation seems to be very outdated as the package has come alongway since this was first made. When are you going to update this lab and the documentation in docs.microsoft.com?

**Comment by Dean-Haas** [comment]
I've emailed Per Mikkelsen who is the PM for this. He's OOF for a week or so.

**Comment by mikkelsen2000** [comment]
Has come a long way indeed - however, the lab is still valid in its current form, though the screenshots are outdated. We will updated this in November/December timeframe

**Comment by malaker** [comment]
Is there any update on this?

**Comment by manb-msft** [comment]
Hi! Is there any update on the labs? The Docs talk about a "PowerApps Checker" service connection that's not used in the labs. It looks pretty outdated. 
Also, I keep getting the same username/password error when I use the Generic Connection (I'm using MSFT Credentials - not sure if MFA is the issue) 
(As I don't have permissions to add user with my @Microsoft account)

**Comment by malaker** [comment]
MFA cannot be skipped I am also struggling with this. I have already sample code that calls the  API on my behalf. In initial point I have to pass MFA after that I obtained token that I am able to refresh and call API.

**Comment by sergeytunnik** [comment]
If you have MFA, you can use application password feature. More details:
- https://www.powerobjects.com/blog/2019/03/20/app-passwords-dynamics-365-apps/
- https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183

**Comment by malaker** [comment]
I believe Conditional Access Policies for Dynamics 365 Service Admin should be setup in that way that MFA is not enforced for those users when they are signed in from trusted locations but maybe its better way. Some organization has strict security rules and for instance app passwords might not be an option and here conditional access policies configured in azure portal comes into the picture and could be considered.

**Comment by phecke** [comment]
@bennyboy23 
After looking into this matter further, we now have a support policy in place.

If you need assistance with the Power Apps build tools or the hands-on labs, post a message to the [Power Apps component framework, ALM & Pro Dev](https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/bd-p/pa_component_framework) forum.
