### ISSUE TITLE
LinearInputControl rendered differently on watch and canvas app

### ISSUE THREAD

**Issue by chienhsiang-hung** [microsoft/PowerApps-Samples#585]
I followed the https://learn.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript?tabs=after#adding-style-to-the-code-component step-by-step carefully.

When I run `npm start watch` it rendered successfully as shown.
![image](https://github.com/microsoft/PowerApps-Samples/assets/77676044/d383ed94-6df1-40f5-bd8d-40e5986eea0b)

But when I imported it into my canvas app it seemed to miss the dragable bar and some properties.
![image](https://github.com/microsoft/PowerApps-Samples/assets/77676044/ed47c63f-3740-46ed-92ba-0dc3bd079408)

seems the watch env is different with the dev env @@

**Comment by jopursle** [comment]
With the most recent sample code from `https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/LinearInputControl`, I'm unable to repro the issue.  In Canvas, the control appears to load fine:
![Image](https://github.com/user-attachments/assets/c5a48111-6b95-4f85-9f20-00ae53bc8789)

Could you try on the most recent samples and Canvas and see if you still see the issue?

As for the missing properties, only ControlValue should show up.  Displaying the type is a test harness only display.

**Comment by JimDaly** [comment]
@jopursle  Thanks for updating the sample code.

Since this was originally opened by @chienhsiang-hung last May, he has probably moved on to other things.  I'm going to close this.
If anyone else experiences the same issue with the latest bits, please create a new issue referencing this one.
