### ISSUE TITLE
Populate Dataverse with Contoso or Northwind data?

### ISSUE THREAD

**Issue by evogelpohl** [microsoft/PowerApps-Samples#591]
Does this project create a full/complete Dataverse demo environment - full of customers, accounts, products, orders, etc? If not, any tools or projects that will do that for me? 500 or so records is fine. Demo only.

I've seen this one https://www.sqlbi.com/tools/contoso-data-generator/, but it creates a SQL db.

Thanks.

**Comment by phecke** [comment]
@evogelpohl I do not know what project you are referring to as you do not mention it in your issue statement. However, you can populate an environment with sample data. See [Add or remove sample data](https://learn.microsoft.com/en-us/power-platform/admin/add-remove-sample-data)
