### ISSUE TITLE
PowerPlatform UserManagement PowerShell Script Requires a Multi-Factor Auth

### ISSUE THREAD

**Issue by inquisitive-identity** [microsoft/PowerApps-Samples#606]
Hi,

I am relatively new to this repo and the coding in general, so I was just wondering if the error I am experiencing with this is related to a wrong, obsolete authentication method regarding Power Platform.

_Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'_

I am trying to run the _Microsoft.PowerPlatform.Administration.UserManagement.psm1_ script.

I have successfully completed all the prerequisites from [this link ](https://github.com/microsoft/PowerApps-Samples/tree/master/powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement#remove-role-assignments-from-given-list-of-users)as well...

Please let me know if you need more information as I am not sure how much info is required from me. :)

Thank you very much in advance!

Best,
Stefan

**Comment by inquisitive-identity** [comment]
**Update**: It seems to have resolved itself somehow as it is now triggering the MFA properly... :)

**Comment by phecke** [comment]
Closing issue.
