### ISSUE TITLE
Error with Azure DevOps Connector Queue a new build

### ISSUE THREAD

**Issue by jdoblams** [microsoft/PowerApps-Samples#614]
Hello Folks,
              Thanks for your time, I was looking to share with you the next scenario

**Context**
I'm looking to send variables over parameters from PowerApps to an ADO YAML Pipeline.

**Issue Description**
While you are working in the Workflow with the "Queue a new build" box it points by default to the REST API "Builds"  ( Link:  https://learn.microsoft.com/en-us/rest/api/azure/devops/build/builds/queue?view=azure-devops-rest-7.1 ) and if you have a YAML pipeline and you want to send variables over Parameters this will retrieve to you a 400 error with this kind of exceptions

`Could not queue the build because there were validation errors or warnings.\r\nAzure DevOps ActivityId: axxxxxec\r\nDetails: {\"ClassName\":\"Microsoft.TeamFoundation.Build.WebApi.BuildRequestValidationFailedException\",\"Message\":\"Could not queue the build because there were validation errors or warnings.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":null,\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146232832,\"Source\":null,\"WatsonBuckets\":null,\"m_logException\":false,\"m_reportException\":false,\"m_errorCode\":0,\"m_logLevel\":\"warning\",\"m_eventId\":3000,\"ValidationResults\":[{\"result\":\"error\",\"message\":\"A value for the '**yourVariableParameter**' parameter must be provided.\"}]}\r\nclientRequestId: xxxxx`

When you have a YAML pipeline this kind of request should be sent to the "Runs" REST API ( link : https://learn.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/run-pipeline?view=azure-devops-rest-7.1 ) 

**Workaround**
Currently to work with a YAML pipeline from Workflows it is necessary the usage of the box "Send an HTTP request to Azure DevOps"

**Request**
Can it be possible to allow to the "Queue a new build" box to work with the Runs API or add a new box to improve the communication with the ADO APIs from PowerApps?

**Comment by phecke** [comment]
@jdoblams We do not provide general support here. You can either file a Support request or post a message to a developer forum. If you have questions about any of our code samples, please submit another issue. Thanks
