### ISSUE TITLE
Failed to create or update the enterprise policy, request body is null

### ISSUE THREAD

**Issue by cpinotossi** [microsoft/PowerApps-Samples#615]
Hello, 
trying to setup enterprisePolicies via Bicep with thr following Bicep Resource Configuration:

~~~bicep
resource ppep 'Microsoft.PowerPlatform/enterprisePolicies@2020-10-30-preview' = {
  name: prefix
  location: 'Germany'
  kind: 'NetworkInjection'
  properties: {
    encryption: {}
    networkInjection: {
      virtualNetworks: {
        value: [
          {
            id: vnet.id
            subnet: {
              name: 'PowerPlatformSubnet'
            }
          }
          {
            id: vnet.id
            subnet: {
              name: 'PowerPlatformSubnet2'
            }
          }
        ]
      }
    }
  }
}
~~~

Does result into the following Error Message:

{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/f474dec9-5bab-47a3-b4d3-e641dac87ddb/resourceGroups/cptdazpowerp/providers/Microsoft.Resources/deployments/deploy","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InputValidationError","message":"Failed to create or update the enterprise policy, request body is null."}]}}

Having a look at PowerApps-Samples\powershell\enterprisePolicies\Common\EnterprisePolicyOperations.ps1 it seems like my settings are all like expected for "NetworkInjection".

QUESTION: Any idea how to fix this error Message,

**Comment by cpinotossi** [comment]
Did manage to solve the issue.

**Comment by robjdav** [comment]
Hello - can you let us know what you did to resolve this? I'm getting the same error

thanks

**Comment by rajeshkrrajjo** [comment]
Please use the previous version API and it works there.
Use API version:  2020-10-30

**Comment by sadjadbp** [comment]
https://github.com/microsoft/PowerApps-Samples/issues/620#issuecomment-2457778323
