### ISSUE TITLE
Unable to build dataverse/webapi/C#-NETx/RetrieveMetadataChanges

### ISSUE THREAD

**Issue by MightyJaker** [microsoft/PowerApps-Samples#622]
1>C:\GitHub\PowerApps-Samples\dataverse\webapi\C#-NETx\RetrieveMetadataChanges\Program.cs(31,73,31,88): error CS0103: The name 'LogicalOperator' does not exist in the current context
1>C:\GitHub\PowerApps-Samples\dataverse\webapi\C#-NETx\RetrieveMetadataChanges\Program.cs(38,77,38,83): error CS0234: The type or namespace name 'Object' does not exist in the namespace 'PowerApps.Samples.Metadata.Types' (are you missing an assembly reference?)
1>C:\GitHub\PowerApps-Samples\dataverse\webapi\C#-NETx\RetrieveMetadataChanges\Program.cs(39,48,39,58): error CS0103: The name 'ObjectType' does not exist in the current context
1>C:\GitHub\PowerApps-Samples\dataverse\webapi\C#-NETx\RetrieveMetadataChanges\Program.cs(49,77,49,92): error CS0103: The name 'LogicalOperator' does not exist in the current context
1>C:\GitHub\PowerApps-Samples\dataverse\webapi\C#-NETx\RetrieveMetadataChanges\Program.cs(57,81,57,87): error CS0234: The type or namespace name 'Object' does not exist in the namespace 'PowerApps.Samples.Metadata.Types' (are you missing an assembly reference?)
1>C:\GitHub\PowerApps-Samples\dataverse\webapi\C#-NETx\RetrieveMetadataChanges\Program.cs(58,46,58,56): error CS0103: The name 'ObjectType' does not exist in the current context

**Comment by JimDaly** [comment]
@MightyJaker 
Thanks for reporting this. Sorry for the delay in addressing it.

Fixed this with PR #637
