### ISSUE TITLE
Power Apps Grid Control in a power pages is not rendering a currency column

### ISSUE THREAD

**Issue by willgart** [microsoft/PowerApps-Samples#626]
Hi,

I want to use the Power Apps Grid Control as a subgrid in a form in a power pages site.
this is working.
but...

my currency columns are not rendered properly, they are empty.
when I edit the cell them I can see the value.

![image](https://github.com/user-attachments/assets/702e00df-f4b4-4e3e-9b3c-30407970490e)

![image](https://github.com/user-attachments/assets/c0e2190b-02f6-44da-a287-a61eb446c4ed)

Any idea?

Thanks.

**Comment by phecke** [comment]
@willgart  Sorry, but we cannot help you with that issue. I suggest you file a Support request.
