### ISSUE TITLE
Dataverse search sample not working

### ISSUE THREAD

**Issue by ciaomatteo** [microsoft/PowerApps-Samples#631]
I'll get this error message when running the dataverse search sample (org service, .net core version).
![image](https://github.com/user-attachments/assets/f6515cfe-cdfc-4013-bdc6-fb2b490ee9f5)

**Comment by bguidinger** [comment]
We are also facing this issue when using the "searchquery" action. It seems like it's running the underlying plugin, but it's encountering an error in the plugin trying to read/parse a Guid. @JimDaly any insight into this?

`ActivityId: f8572f6a-4f02-49e5-8e41-551a73164424`

![Image](https://github.com/user-attachments/assets/209fbcd9-e2c5-48c1-b770-1cd326b9b264)

**Comment by JimDaly** [comment]
@ciaomatteo and @bguidinger 
I can repro this issue. I've raised it as a bug with the dev team. There are also reports from support about this.

I know the sample worked when we shipped it, IDK when it stopped working.

AFAIK, there is nothing more I can do, so I'll close this for now.

**Comment by andi-meier** [comment]
Is there any news on this or has anyone found a workaround?

**Comment by JimDaly** [comment]
> Is there any news on this or has anyone found a workaround?

None yet, but I've pinged the team to remind them to assign someone to the bug.

Workarounds would be to use Web API, and Dataverse Service Client has an [ExecuteWebRequest](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/xrm-tooling/use-xrm-tooling-to-execute-web-request) method to send requests to the Web API, but this shouldn't be required.

**Comment by andi-meier** [comment]
Thanks for the feedback, that's good news. I will test it with the web api in the meantime. 

I find it strange that this feature has not been working for several months. Is nobody using that in production?

**Comment by Toftager** [comment]
> Thanks for the feedback, that's good news. I will test it with the web api in the meantime.
> 
> I find it strange that this feature has not been working for several months. Is nobody using that in production?

We are also looking into using this functionality, but are a bit concerned about using it, as it seems there is not really any traction on it. 

Is this the way to go or should we look in other directions for wide system searching?

**Comment by JimDaly** [comment]
The feature works, but [as you can see in the docs](https://learn.microsoft.com/power-apps/developer/data-platform/search/overview), there are three different endpoints that expose it. Four if you include the deprecated v1.0 endpoint.

The bug that impacts this sample only has to do with the .NET SDK. Bug is a regression.  ETA of fix is March + 6 weeks.

We haven't documented any other system wide search capability. This is the way to go.

**Comment by Toftager** [comment]
> The feature works, but [as you can see in the docs](https://learn.microsoft.com/power-apps/developer/data-platform/search/overview), there are three different endpoints that expose it. Four if you include the deprecated v1.0 endpoint.
> 
> The bug that impacts this sample only has to do with the .NET SDK. Bug is a regression. ETA of fix is March + 6 weeks.
> 
> We haven't documented any other system wide search capability. This is the way to go.

Great, we'll continue down this path then. 

Thanks for the feedback Jim :)

**Comment by LarsBauer** [comment]
Thanks for the update Jim! Is it possible to give us a ping in this thread once its resolved? For now I try to implement my use case with the `ExecuteWebRequest` workaround but apparently its not that convenient to use. I cannot imagine how this issue still persists for multiple months already. Luckily we dont use this feature in production yet.
