### ISSUE TITLE
Help/Advice for PCF for canvas app to upload large file

### ISSUE THREAD

**Issue by krunal039** [microsoft/PowerApps-Samples#636]
I’m using PnPJs to create a PCF control for uploading large files to SharePoint within a canvas app. The code below is working while editing the canvas app, along with the redirection URI : https://authoring.eu-il109.gateway.prod.island.powerapps.com/v3.24095.15.310953622/embed/

`
import { IInputs, IOutputs } from "./generated/ManifestTypes";
import type { MSALOptions } from "@pnp/msaljsclient";
import { spfi, SPBrowser } from "@pnp/sp";
import { MSAL, getMSAL } from "@pnp/msaljsclient";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/site-users/web";

export class pcfspolargeupload implements ComponentFramework.StandardControl<IInputs, IOutputs> {

constructor()
{

}

public async init(context: ComponentFramework.Context, notifyOutputChanged: () => void, state: ComponentFramework.Dictionary, container:HTMLDivElement): Promise
{
let _notifyOutputChanged: () => void
let _context: ComponentFramework.Context
let _spContext: any

const options: MSALOptions = {
    configuration: {
        auth: {
            authority: "https://login.microsoftonline.com/[TenantID]/",
            clientId: "[AppID]",
        },
        cache: {
            claimsBasedCachingEnabled: true // in order to avoid network call to refresh a token every time claims are requested
        }
    },
    authParams: {
        forceRefresh: false,
        scopes: ["https://tenant.sharepoint.com/.default"],
    }
};

const sp = spfi("https://tenant.sharepoint.com/").using(SPBrowser(), MSAL(options));

const user = await sp.web.currentUser();

// For logout later on
const msalInstance = getMSAL();
const currentAccount = msalInstance.getActiveAccount();

const list = sp.web.lists.getByTitle("Documents");

// we can use this 'list' variable to run more queries on the list:
const r = await list.select("Id")();

// log the list Id to console
console.log(r.Id);

container.appendChild(document.createTextNode(r.Id));
}

public updateView(context: ComponentFramework.Context): void
{
}
public getOutputs(): IOutputs
{
return {};
}

public destroy(): void
{
}
}`

Question/Request
When I publish the app and access it, the redirection URI changes to: https://runtime-app.powerplatform.com/publishedapp/e/default-cc83b6ac-505f-4efc-a552-a2c7bfa6d7e3/preloadindex/V1. The popup doesn’t close, and I’m unsure what I’m doing wrong. What steps should I take to get PnPJs working with my AAD app to upload large files to SharePoint via PCF control in Canvas app?

![Image](https://github.com/user-attachments/assets/368445e5-62c0-4a90-a1cb-68fa39ee6696)

**Comment by JimDaly** [comment]
@krunal039 
Sorry for the delay in responding. This repository contains Power Apps samples, including PCF samples, but not PnPJs. PnPJs appears to be distributed here: https://github.com/pnp/pnpjs. If you haven't already resolved the problem, perhaps you can open an issue there.
