### ISSUE TITLE
GlobalDiscovery sample broken

### ISSUE THREAD

**Issue by JimDaly** [microsoft/PowerApps-Samples#64]
The sample has a number of issues:
1. Failed to load using Visual Studio 2019, had to use VS 2017
2. There was a issue with the NugGet package where I had to click some Restore button to avoid build issues with VS 2017
3. The sample was recently updated [here](https://github.com/microsoft/PowerApps-Samples/commit/fd4816c9ff18e31e05c0aa45ee84874fd6b6d8ba#diff-76b7cc561a3342d4953fc346998420ef) to replace the Authority URL.
Old value: https://login.windows.net/common
New value: https://login.microsoftonline.com

Sample wouldn't run until I switched back to the old value

4. This sample really ought to be updated to use the newer version of ADAL, then remove all the App.Config since this sample isn't using CrmServiceClient anyway.

**Comment by MattB-msft** [comment]
Addressed with this PR: https://github.com/microsoft/PowerApps-Samples/pull/66 to remove the root issue
