### ISSUE TITLE
PowerApps - Modern Forms Tabulation Index not working correctly

### ISSUE THREAD

**Issue by DAKK-chaloon** [microsoft/PowerApps-Samples#647]
Hi,

I'm using a SharePoint customized form with PowerApps that includes a modern Edit Form.
The form contains many controls, and I created a navigation system using "sections" to hide or show components based on the selected section.

Unfortunately, it seems that the tab index is not properly configured for these controls.
When I publish the application, tabbing works correctly only for the elements visible at the time of publishing. For the others, the tab index appears to be random.

Is this the expected behavior? If so, what can I do to address this issue? This situation makes the application quite uncomfortable to use.

**Comment by phecke** [comment]
@DAKK-chaloon Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://powerpages.microsoft.com/en-us/support/ Closing this issue.

We address questions and issues about our sample code here.
