### ISSUE TITLE
PowerApps Build Tools Tutorial Organization Name cannot be null

### ISSUE THREAD

**Issue by rramhapgb** [microsoft/PowerApps-Samples#68]
Getting a consistent error in module 2 of tutorial, during PowerApps Export Solution.

##[error]Organization cannot be null or empty.
Parameter name: Organization Name

I've double-checked entries and wondering if this has been updated.

##[section]Starting: PowerApps Export Solution 
==============================================================================
Task         : PowerApps Export Solution
Description  : PowerApps Export Solution
Version      : 0.1.7
Author       : Microsoft
Help         : [More Info](https://aka.ms/buildtoolsdoc)
==============================================================================
##[error]Organization cannot be null or empty.
Parameter name: Organization Name
##[section]Finishing: PowerApps Export Solution

**Comment by Dean-Haas** [comment]
Not sure who would own this sample data

**Comment by phecke** [comment]
@rramhapgb 
Is this issue related to the build tool hands-on labs that you downloaded from this repo? If so, let us know in a followup comment.

If you need assistance with the Power Apps build tools, post a message to the Power Apps component framework, ALM & Pro Dev forum.

**Comment by phecke** [comment]
@rramhapgb 
After looking into this matter further, we now have a support policy in place.

If you need assistance with the Power Apps build tools or the hands-on labs, post a message to the [Power Apps component framework, ALM & Pro Dev](https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/bd-p/pa_component_framework) forum.

**Comment by sekadiv** [comment]
I am facing this issue it is giving as organization name cannot be null even though i have created service connection
