### ISSUE TITLE
Solution will not build

### ISSUE THREAD

**Issue by MichaelSchofeld** [microsoft/PowerApps-Samples#74]
I get a number of errors when I try to build the solution.  Some files are hardcoded to specific locations and others don't even exists in the solution.

![Errors](https://user-images.githubusercontent.com/38990185/70798925-40e02800-1d76-11ea-946a-d7fc0b7d93da.JPG)

**Comment by Nkrb** [comment]
@MichaelSchofeld Thanks for the feedback. can you let us know the specific sample that you are facing this issue.
