### ISSUE TITLE
HttpClient Example Design Issue

### ISSUE THREAD

**Issue by altmank** [microsoft/PowerApps-Samples#79]
According to https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.8, "HttpClient is intended to be instantiated once per application, rather than per-use"

The example provided at https://github.com/microsoft/PowerApps-Samples/blob/master/cds/orgsvc/C%23/WebAccessPlugin/WebAccessPlugin/HttpClientPlugin.cs violates this in its design

**Comment by KumarVivek** [comment]
@JimDaly/@Phecke Can you please address this.

**Comment by JimDaly** [comment]
The guidance assumes you are building an app and can re-use the HttpClient.
This example is to make an outbound call from within a plug-in. There is no way for a plug-in developer to define a re-usable HttpClient that spans multiple plug-ins.

In this sample, only one call is being made, so the design is acceptable.

Agree that if the plug-in needs to make multiple outbound calls there is opportunity to re-use the client.

If anyone wishes to submit a PR with a better example, we could consider applying it.

**Comment by altmank** [comment]
Hey @JimDaly, to help me better understand use cases in which this guidance may apply can you let me know what would happen in this scenario:

A plugin instantiates a static class and within that class a static instance of the HttpClient and that static class is used by that plugin to send a request using that client. If that plugin is then called 100 times, wouldn't that result in reuse of the HttpClient inline with the recommendations or is there something happening here as part of plugin execution design that would prevent that reuse?

**Comment by JimDaly** [comment]
First, I hope you aren't making 100 outbound calls within a plug-in.

The reason for the guidance is "_Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors._"

I don't disagree with what you are saying, but as the host of the sandbox service where these plug-ins are running, the pattern isn't one that has caused us any problems yet. We don't expect people to make hundreds of outbound calls from within a single plug-in step, which should only exist for a period of seconds compared to an app process which could run for an indefinite period. You aren't wrong, it is just a different runtime context where we aren't so concerned about the same issues that guidance appears to be focused on.

We don't have a strong enough opinion about it to try and tell people how they should do it, or take on the work to re-write this sample when we could be doing more productive things. 
If you want to re-write it, please do. It is on Github for just this reason.

If we ever tie this pattern to a problem in the future and the guidance provided is key, we would update the sample.

**Comment by altmank** [comment]
Yes I agree with your statements regarding the documentation example, thank you very much for addressing that!. My question has kind of branched off a bit from that out of curiosity. I'm genuinely curious if static class instances are shared across plugin executions and if so, to what extent before being re-instantiated. A fairly straightforward use case I can think of is a plugin triggered by an action, that when called, sends a HTTP request. So if I call that action 100 times in quick succession, meaning 100 different executions of that plugin, I'm curious if that static plugin assembly HTTPClient would get reused or if some design mechanism of Dynamics plugin architecture would prevent re-use. I understand if you can't answer this question but it would help me greatly to know! Thank you for your time.

**Comment by sergeytunnik** [comment]
@altmank actually answer for your question depends on number of parameters of D365 deployment. Key factors are:
- isolation mode: sandbox\none
- step execution mode: sync\async
- number of servers in deployment group

Let's assume that we are talking about D365 online or PowerApps deployment, not on-premise. We may have only sandbox plugins in online deployment. From my experience plugin\activity get instantiated for every single call\execution and then immediately torn down when used via sandbox. Thus HttpClient won't be reused.
It would worked well to have HttpClientFactory in IServiceProvider parameter of Execute method. :)

P.S. That's my personal experience and might not exactly represent actual behavior of PowerApps.

**Comment by altmank** [comment]
@sergeytunnik Thank you for your reply! That information is helpful.

What did you mean by this:

> It would worked well to have HttpClientFactory in IServiceProvider parameter of Execute method. :)

**Comment by sergeytunnik** [comment]
I mean it would be great if D365 provided factory for HttpClient and we wouldn't have to manage HttpClients ourselves. D365 would manage lifetime of HttpClient instances. Similar to how it is used in ASP NET Core: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1
