### ISSUE TITLE
Bad Request (400) when logging into CRM in Pipeline Create Export from Dev

### ISSUE THREAD

**Issue by NPrice99** [microsoft/PowerApps-Samples#83]
Power Platform ALM Workshop : Module2 - Item 30 fails when running the pipeline 👎 

Details                                            Agent job 1                                                           1 error(s), 0 warning(s)                                                                      Failed to connect to         instance: https://Organisation ID.crm11.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM | Details | Agent job 1                                                           1 error(s), 0 warning(s)                                                                      Failed to connect to         instance: https://organisation ID.crm11.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM | Agent job 1 | 1 error(s), 0 warning(s)                                                                      Failed to connect to         instance: https://Organisation ID.crm11.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM | 1 error(s), 0 warning(s) |   | Failed to connect to         instance: https:// Organisation ID.crm11.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM
-- | -- | -- | -- | -- | -- | -- | --
Details
Agent job 1                                                           1 error(s), 0 warning(s)                                                                      Failed to connect to         instance: https://Organisation ID1.crm11.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM | Agent job 1 | 1 error(s), 0 warning(s)                                                                      Failed to connect to         instance: https://Organisation ID.crm11.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM | 1 error(s), 0 warning(s) |   | Failed to connect to         instance: https://org9a7eff11.crm11.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM
Agent job 1
1 error(s), 0 warning(s)                                                                      Failed to connect to         instance: https://Organisation ID.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM | 1 error(s), 0 warning(s) |   | Failed to connect to         instance: https://<Organisation ID>.crm11.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM
1 error(s), 0 warning(s)
  | Failed to connect to         instance: https://Organisation ID.dynamics.com/.         Please verify your credentials for *** and instance url. ERROR         REQUESTING Token FROM THE Authentication context ERROR REQUESTING Token         FROM THE Authentication contextOne or more errors occurred. =>         AADSTS50126: Error validating credentials due to invalid username or         password. Trace ID: e3e48a84-99ba-45f4-b600-421f9214c700 Correlation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14         18:13:24Z => Response status code does not indicate success: 400         (BadRequest). =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to connect to CRM: AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         One or more errors occurred. => AADSTS50126: Error validating         credentials due to invalid username or password. Trace ID:         e3e48a84-99ba-45f4-b600-421f9214c700 Correlation ID:         f0421c7c-ffae-499e-804e-25c2c6c2e1fc Timestamp: 2020-01-14 18:13:24Z         => Response status code does not indicate success: 400 (BadRequest).         =>         {"error":"invalid_grant","error_description":"AADSTS50126:         Error validating credentials due to invalid username or         password.\r\nTrace ID: e3e48a84-99ba-45f4-b600-421f9214c700\r\nCorrelation         ID: f0421c7c-ffae-499e-804e-25c2c6c2e1fc\r\nTimestamp: 2020-01-14         18:13:24Z","error_codes":[50126],"timestamp":"2020-01-14         18:13:24Z","trace_id":"e3e48a84-99ba-45f4-b600-421f9214c700","correlation_id":"f0421c7c-ffae-499e-804e-25c2c6c2e1fc","error_uri":"https://login.microsoftonline.com/error?code=50126"}:         Unknown errorUnable to Login to Dynamics CRM Unable to Login to         Dynamics CRM

I have checked that Username and Password are correct.  If they were wrong I would expect a 403 error.

Details I suspect in the manual are a little out of date.

**Comment by AnkitGirgas** [comment]
Facing similar issue in Export solution task, Failed to connect to instance: https://<tenant-name>.crm.dynamics.com/. Please verify your credentials for *** and instance url

**Comment by phecke** [comment]
@NPrice99 
Is this issue related to the build tool hands-on labs that you downloaded from this repo? If so, let us know in a followup comment.

If you need assistance with the Power Apps build tools, post a message to the [Power Apps component framework, ALM & Pro Dev](https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/bd-p/pa_component_framework) forum.

**Comment by NPrice99** [comment]
Yes it was related to the build tool hands on labs that I downloaded from this repo.

**Comment by phecke** [comment]
@NPrice99 
After looking into this matter further, we now have a support policy in place.

If you need assistance with the Power Apps build tools or the hands-on labs, post a message to the [Power Apps component framework, ALM & Pro Dev](https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/bd-p/pa_component_framework) forum.
