### ISSUE TITLE
PowerApps Unpack Solution not working with Enviroment variable 

### ISSUE THREAD

**Issue by saadnadir** [microsoft/PowerApps-Samples#92]
Hi i am getting the following error as soon as i introduce an enviroment variable in my solution that i am unpacking in my pipeline.

![Error checker](https://user-images.githubusercontent.com/39247752/74451518-c1420880-4e4d-11ea-9175-61a2fd1321c9.PNG)

**Comment by phecke** [comment]
@saadnadir 
If you need assistance with the Power Apps build tools, post a message to the [Power Apps component framework, ALM & Pro Dev](https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/bd-p/pa_component_framework) forum.

**Comment by phecke** [comment]
@saadnadir 
If this issue is related to the build tools hands-on labs that you downloaded here, then let us know in a followup comment.
