### ISSUE TITLE
Missing Files in GenerateEntityDiagram solution

### ISSUE THREAD

**Issue by sonorone** [microsoft/PowerApps-Samples#94]
There are missing files in the PowerApps-Samples/cds/GenerateEntityDiagram/

- LoginUX/ExampleLoginForm.xaml
- LoginUX/ExampleLoginForm.cs
- App.config
- MyOrganizationSdkTypes.cs
- SampleHelpers.cs
- SystemUserProvider.cs

**Comment by Nkrb** [comment]
@sonorone Thanks for the feedback. We have fixed the sample and pushed it live. Closing the issue.
