### ISSUE TITLE
PowerApps Backup Environment task error in DevOps running with user with mfa enabled

### ISSUE THREAD

**Issue by itaskov** [microsoft/PowerApps-Samples#96]
Hello,

PowerApps Backup Environment devops task failed with the error bellow when the Service connection's user has mfa enabled. It failed also using "app password" for the same account.

2020-02-20T14:53:43.6107350Z ##[section]Starting: PowerApps Import Solution 
2020-02-20T14:53:43.6211569Z ==============================================================================
2020-02-20T14:53:43.6212088Z Task         : PowerApps Import Solution
2020-02-20T14:53:43.6212532Z Description  : PowerApps Import Solution
2020-02-20T14:53:43.6212753Z Version      : 0.1.10
2020-02-20T14:53:43.6213228Z Author       : Microsoft
2020-02-20T14:53:43.6213516Z Help         : [More Info](https://aka.ms/buildtoolsdoc)
2020-02-20T14:53:43.6214047Z ==============================================================================
2020-02-20T14:53:46.9918491Z ##[error]Failed to connect to instance: <Instance name removed>. Please verify your credentials for *** and instance url.
ERROR REQUESTING Token FROM THE Authentication context
ERROR REQUESTING Token FROM THE Authentication contextOne or more errors occurred. => AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'removed'.
Trace ID: f5c6d886-a52c-4c3e-9d06-1cde6e5f1e00
Correlation ID: 38931600-2d8b-4ba4-b238-6febd2a11cec
Timestamp: 2020-02-20 14:53:46Z => Response status code does not indicate success: 400 (BadRequest). => {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'removed'.\r\nTrace ID: f5c6d886-a52c-4c3e-9d06-1cde6e5f1e00\r\nCorrelation ID: 38931600-2d8b-4ba4-b238-6febd2a11cec\r\nTimestamp: 2020-02-20 14:53:46Z","error_codes":[50076],"timestamp":"2020-02-20 14:53:46Z","trace_id":"f5c6d886-a52c-4c3e-9d06-1cde6e5f1e00","correlation_id":"38931600-2d8b-4ba4-b238-6febd2a11cec","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}: Unknown errorUnable to connect to CRM: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'removed'.
Trace ID: f5c6d886-a52c-4c3e-9d06-1cde6e5f1e00
Correlation ID: 38931600-2d8b-4ba4-b238-6febd2a11cec
Timestamp: 2020-02-20 14:53:46Z
2020-02-20T14:53:47.0313302Z ##[section]Finishing: PowerApps Import Solution

**Comment by phecke** [comment]
@itaskov 
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://powerapps.microsoft.com/support/>.

Closing this issue.

**Comment by itaskov** [comment]
Peter,

I was told by the powerapps support to open an issue here because the build
tools are still preview and there is no service connection in DevOps
supporting mfa.

I will open a support request again with the powerapps support.

**Comment by phecke** [comment]
@itaskov 
Unfortunately, we do not have the knowledge to help you on this issue. However, I did find a private thread that mentions use of MFA in ADO pipeline. Perhaps this info would help you.

_...we are aware of the limitation and our next release should include full support for service principals so that you can authenticate with a headless service account.  In the meantime, you should use a user credential with MFA disabled for that account._

**Comment by phecke** [comment]
@itaskov Worst case, have Support contact me and I can refer them to an internal contact that may be able to help.

**Comment by itaskov** [comment]
Peter,

Thank you very much. I have just opened a service request and will update
it to include your contact information.

**Comment by phecke** [comment]
@itaskov New information
If you need assistance with the Power Apps build tools, post a message to the [Power Apps component framework, ALM & Pro Dev](https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/bd-p/pa_component_framework) forum.
