### ISSUE TITLE
Deprecation of Office365 authentication type

### ISSUE THREAD

**Issue by baibhav-82** [microsoft/PowerApps-Samples#98]
Referring to https://docs.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-common-data-service

Does this impact plugins as well? What are its alternatives?

**Comment by sergeytunnik** [comment]
Hi.
I'm not MSFT guy.
In plugins we always get preconfigured instance of IOrganizationService.
It will affect connectivity to CDS from external systems. Or if in Plugin you are connecting to another CDS instance in another tenant.

**Comment by phecke** [comment]
@baibhav-82
Yes, Sergey is correct. When a plug-in executes it gets a pre-configured and authenticated connection to the Organization service that is passed to the plug-in in the execution context. As long as you use that connection, the plug-in would not be impacted by this change.
